### ISSUE TITLE
Trucks Overview / Carousel 

### ISSUE THREAD

**Issue by hannessolo** [hlxsites/vg-volvotrucks-us#10]
<img width="1250" alt="Screenshot 2023-02-15 at 14 55 18" src="https://user-images.githubusercontent.com/24207564/219063043-786f776f-369a-4a32-9f27-6e4f39b5a7d2.png">

Including responsive behaviour (becomes carousel)

**Comment by Buuhuu** [comment]
To be reused for the carousels like "SOLUTIONS BUILT FOR YOU" the following pages. The mobile experience is the same. For the desktop experience we would add a modifier to the block: `Carousel (as grid on desktop)`.

https://www.volvotrucks.us/trucks/vnr-electric/
<img width="736" alt="Screenshot 2023-02-22 at 11 10 13" src="https://user-images.githubusercontent.com/558094/220589356-1abb609a-a628-4b79-870b-64a3860441d6.png">


https://www.volvotrucks.us/trucks/vnr/
<img width="1206" alt="Screenshot 2023-02-22 at 11 10 16" src="https://user-images.githubusercontent.com/558094/220589293-936fbb49-a75c-4cae-bbe8-a6c966626ba2.png">
