### ISSUE TITLE
Teaser Grid Layout Variation

### ISSUE THREAD

**Issue by andreibalanescu** [hlxsites/vg-volvotrucks-us#111]
We have several variations of the Teaser Grid Layout here: 
https://www.volvotrucks.us/our-difference/
https://www.volvotrucks.us/our-difference/driver-productivity/ (hero only)
https://www.volvotrucks.us/trucks/vnr/top-ten/
https://www.volvotrucks.us/trucks/vnr/top-ten/design/

![image](https://user-images.githubusercontent.com/126146302/225303949-3ec59955-582c-4461-a0da-b8e4264c78c8.png)

**Comment by TomaszDziezykNetcentric** [comment]
This block is not needed anymore
