### ISSUE TITLE
Defect: Specification table: Braking Energy row is not correctly displayed in specification table (root cause: multiline data for few rows) & other issues

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#114]
**Steps:**
1. Navigate to the https://specifications--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/vnl/specifications/
2. Scroll to the specifications section 
3. Validate the table headers in iphone SE mobile viewport using webbrowser(responsive)

**Expected:**
1. The  Braking Energy row data should be displayed correctly
2. The note '*when configured with 6 battery offering' should be displayed below specification table 
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/225318632-e2e531c7-a975-4f8c-bd4e-63e847b35270.png">
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/225322805-a9f13273-8526-47ea-a141-90d270853235.png">

**Actual:**
1. The  Braking Energy row data is not displayed when upper columns have more data ( e.g. in case of  **VNR Electric 6X2 Tractor**, **VNR Electric 6X4 Tractor** )
2. The note below specification table is not displayed   **"*when configured with 6 battery offering"**
3. The truck model description is no more displayed with this new implementation unlike earlier approach 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/225318868-b646de9a-ff72-4bf8-91e0-b8ab00e90cac.png">

![image](https://user-images.githubusercontent.com/125972657/225323265-b5003aec-f4f1-4410-bd44-bfc2275425b7.png)

**Comment by Buuhuu** [comment]
> The truck model description is no more displayed with this new implementation unlike earlier approach

The description above the table does not belong to the specifications block but a carousel block above the specifications. This just no on the page.

**Comment by girishdigrajkar** [comment]
@Buuhuu : The note below specification table is not displayed *"when configured with 6 battery offering" thus, please fix it ... thanks
