### ISSUE TITLE
Defect : Global Styling - There is a margin space missing between the Navigation bar and the main content area

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#118]
On the volvotrucks.us website there is a margin space between the Navigation bar and the main contet that is missing from https://main--vg-volvotrucks-us--hlxsites.hlx.page/

*Steps to reproduce:*
1. Open https://www.volvotrucks.us/
2. Open https://main--vg-volvotrucks-us--hlxsites.hlx.page/
3. Compare the margin space under the grey Navigation bar

*Expected result*
There is a margin space between the grey Navigation bar and the main content area

<img width="1781" alt="image (191)" src="https://user-images.githubusercontent.com/127409602/225640840-dfa30a7a-58ec-49c0-a3f5-9849679cc74c.png">

*Actual result*
There is no margin space between the grey Navigation bar and the main content area

<img width="1781" alt="image (192)" src="https://user-images.githubusercontent.com/127409602/225641071-880e1e59-f1fe-401d-9b05-bd491e080078.png">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed

**Comment by Buuhuu** [comment]
This is now not working anymore for hero images https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed per above
