### ISSUE TITLE
Defect: Minor: center carousel grid items ( related to #52 & #58) Availability Section text font is incorrect 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#125]
Steps:
1. Navigate to https://issue-52--vg-volvotrucks-us--hlxsites.hlx.page/drafts/drudolph/powertrain/d13tc/
2. Validate the text displayed in 'Availability' section  for font 

Expected:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/225818225-aea55c5f-82e0-469e-86fe-f2665a62d84b.png">

Actual:
Font displayed is not as expected, please see below analysis :
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/m_ambin03198/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/m_ambin03198/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Text | Expected Font | Actual Font
-- | -- | --
AVAILABILITY | 24PX   VOLVONOVUMMEDIUM, SansSerif | **30PX**   VOLVONOVUMMEDIUM
COMPATIBLE WITH THE D13TC | 24PX   VOLVONOVUMMEDIUM, SansSerif | **30PX**   VOLVONOVUMMEDIUM
A truly unique engine for a truly unique truck. Available only   for VNL, the D13TC brings even better fuel economy savings and more   power. | 16 PX VOLVONOVUMREGULAR | **16 PX VOLVONOVUM**
VNL Series | 16 PX VOLVONOVUMREGULAR | **16 PX VOLVONOVUM**
The shape of trucks to come. | 16 PX VOLVONOVUMREGULAR | **16 PX VOLVONOVUM**

</body>

</html>

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/225818273-5a16d81b-e17e-455e-b5c2-b422fa220278.png">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
