### ISSUE TITLE
style/block magazine articles

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/vg-volvotrucks-us#131]

**Comment by girishdigrajkar** [comment]
Observed that the section Title( font is 48px unlike 60px) and the button are not centrally aligned so, presuming that this ticket will take care of this.

**Comment by Andrei-Boiangiu** [comment]
Minor possible content related issue here

some magazine articles have the Topic in the Title 
see this example
![image](https://user-images.githubusercontent.com/127409602/233103319-06b34e1a-a3ef-42c7-8dff-b0e9afecee57.png)
