### ISSUE TITLE
Defect:Major: Main Navigation: Search functionality is not working

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#133]
**Steps:**
Navigate to https://issue-4-3--vg-volvotrucks-us--hlxsites.hlx.page/ 
Enter 'AEM' in search box and click on magnifier glass icon

**Expected:**
The search should yield results

**Actual:**
Nothing happens when clicked on search icon
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/226297949-4435f6c4-4e00-48db-9992-983c3aa6297d.png">

**Comment by bpauli** [comment]
Closing as duplicate. This issue is already covered in #130

**Comment by girishdigrajkar** [comment]
agree to defect closure ...thanks
