### ISSUE TITLE
Truck Confgurator (https://build.volvotrucks.com)

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/vg-volvotrucks-us#14]
https://www.volvotrucks.us/trucks/build/

**Comment by dkuntze** [comment]
https://www.volvotrucks.us/trucks/build/

**Comment by Joesturbo** [comment]
Any link in Navigation or on pages should redirect to new window - https://build.volvotrucks.com

**Comment by synox** [comment]
correction: url is https://build.volvotrucks.us/

**Comment by Andrei-Boiangiu** [comment]
Note: Clicking on the **Build Your VNR** or **Build your VNL** links from the *sub-navigation bar* of the respective truck pages does **not** open the build.volvotrucks.us in a new tab but it opens it on the same page

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/127409602/233049233-715d4eeb-5035-4eca-8da2-3593781ffb49.png">

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/127409602/233049399-1957867f-c326-43ee-8dfa-fd9f2d79ccb8.png">

**Comment by synox** [comment]
@Andrei-Boiangiu now also fixed in sub-nav
