### ISSUE TITLE
Defect: iPhone SE / Mobile View - Text and Icons for Header buttons are slightly misalignned

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#141]
On iPhone SE / Mobile View - the Text and Icons when opening the Navigator Menu in the Header are slightly misaligned

**Steps to reproduce:**
1. Open https://www.volvotrucks.us/ and view in iPhone SE / Mobile View (or Samsung Galaxy S8+ etc)
2. Open the Navigator Menu from the Header on the upper right side
3. Open https://main--vg-volvotrucks-us--hlxsites.hlx.page/ and view in iPhone SE / Mobile View (or Samsung Galaxy S8+ etc)
4. Open the Navigator Menu from the Header on the upper right side
5. Compare the Find a Dealer, Purchase a Truck etc buttons on top of the menu and notice the misalgnment of the icons and text

**Expected result**
see the buttons from the upper half of this screenshot

<img width="475" alt="image (197)" src="https://user-images.githubusercontent.com/127409602/226938727-36d594bb-e361-459c-ad59-5ba79cee2520.png">

**Actual result**
see the buttons from the bottom half of this screenshot

<img width="475" alt="image (197)" src="https://user-images.githubusercontent.com/127409602/226939015-2792facc-fc55-493b-a1ab-e866b7acc4fc.png">

**Comment by Buuhuu** [comment]
We can adjust the spacing between the items to match the original style (4%) but we will not achieve a pixel perfect match as we use a flex box to position the items vertically in the middle and right from the closing button. This causes the percentage to be slightly different to the original site. Also the original site uses a padding left of the tools nav and a margin of the first item which causes the first item to not be aligned with the text of the menu below on viewports between 480px and 768px. We should have a fixed padding left of 15px for that.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
