### ISSUE TITLE
Defect: minimal - iPhone SE / Mobile View - On Navigation bar Menu when a Page dropdown is open the rest of the pages are displayed beneath the subpages

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#142]
On a Mobile View, when opening the Navigation bar Menu and clicking on a Page dropdown (for ex: Trucks) the rest of the dropdowns are displayed in the menu list beneath the subpages for Trucks. 
On volvotrucks.us, when opening a Page dropdown in the Menu only the subpages are displayed and if the user wants to go to another Page dropdown in the Menu- he has to go back to the Main Menu

**Steps to reproduce:**
1. Open https://www.volvotrucks.us/ and go to Mobile view
2. Click on the Menu icon on the upper right side - Navigator bar Menu is displayed
3. Click to expand one of the pages in the Menu (for ex Trucks)
4. Repeat steps 1 to 3 on https://main--vg-volvotrucks-us--hlxsites.hlx.page/splash/ 
5. Compare the two views
6. Notice that on https://www.volvotrucks.us/  only the subpages for Trucks are displayed in the menu list and if you want to expand another page you need to go back while on https://main--vg-volvotrucks-us--hlxsites.hlx.page/splash/  the other Pages are displayed below the subpages that were expanded

 **Expected result**
 see left side of image
 
<img width="1697" alt="image (198)" src="https://user-images.githubusercontent.com/127409602/227146938-e1cd2369-59e7-4c6f-8985-c06c9958314c.png">

**Actual result**
see right side of image

<img width="1697" alt="image (198)" src="https://user-images.githubusercontent.com/127409602/227146996-dfc17b7b-107b-4a75-b1a3-ae577d40eec0.png">

**Comment by Buuhuu** [comment]
This has been discussed in one of the standups and we said that it is probably a misbehaviour in the old page.
