### ISSUE TITLE
Defect: Minor: Press Releases: Title 'Press Releases' font size, allignment is incorrect 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#145]
**Steps:**
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
2. Validate the title of 'Press Releases' section

**Expected:**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/227449149-5d8c7740-b458-4d6f-bfdc-b64062d059ea.png">

**Actual:**
**The font size for 'Press Releases' should be 60px unlike 46px also, the text should be aligned to centre.**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/227450270-ddbe9caa-e4b9-4ef4-97c0-6d1601edf586.png">

**Comment by andreibalanescu** [comment]
This is weird, because the title is already set up as Centered, but it doesn't get rendered. I feel like Dev involvement is needed here.
