### ISSUE TITLE
Defect: minimal - iPhone SE / Mobile View - Teaser cards - Image on Teaser card is slightly larger and margin space between Teaser cards is bigger

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#147]
On Mobile view, the Images on Teaser cards are slightly larger ( more margin space left and right) and the margin space between Teaser cards is also slightly bigger

**Steps to reproduce:**
1. Open https://www.volvotrucks.us/ on Mobile view and scroll down to the Teaser cards section
2. Open https://main--vg-volvotrucks-us--hlxsites.hlx.page/ on Mobile view and scroll down to the Teaser cards section
3. Notice and compare the image size / left and right margin on Images 
4. Notice and compare the space between the two Teaser cards

**Expected result**
Image size and space between the two Teaser cards should be slightly smaller - see left side of the two screenshots
<img width="1744" alt="image (201)" src="https://user-images.githubusercontent.com/127409602/227486871-e1ce2b8a-0c32-4711-93f2-1b44e5bae784.png">

<img width="1744" alt="image (202)" src="https://user-images.githubusercontent.com/127409602/227486974-62bf8f93-cb42-4b55-b200-9ad88fd85182.png">

**Actual result**
Image size and space between the two Teaser cards is slightly bigger - see right side of the two screenshots

<img width="1744" alt="image (201)" src="https://user-images.githubusercontent.com/127409602/227487261-2bc140a8-6ec0-4ad7-87e1-54d7d6889f4d.png">

<img width="1744" alt="image (202)" src="https://user-images.githubusercontent.com/127409602/227487310-4739dbca-af8b-4b11-a1fd-3c64a1cbf768.png">

**Comment by Buuhuu** [comment]
This was added to match the styles of other teaser cards (even on the same page). Apparently the image + heading + text combination that is in a row on desktop and stacked on mobile (we refer to it as teaser cards) has different implementations on the original page. 

The 3 teaser cards at the end of https://www.volvotrucks.us/ (News & Stories, ...) have a row gap on mobile of 60px, the teasers earlier have a row gap of 15px. Both have a column gap of 30px. 

Maybe the easiest is to use the 30px for both column and row gap.

**Comment by Buuhuu** [comment]
@Andrei-Boiangiu we should check with the customer if that is acceptable.

**Comment by Andrei-Boiangiu** [comment]
@Buuhuu can you let me know when and if this is verified with the customer and if it should be reopened or not? Thank you

**Comment by Andrei-Boiangiu** [comment]
Note: I added "question" label as per above check to be made
