### ISSUE TITLE
Defect: Major: Hub filter component is not displayed

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#148]
**Steps:**
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/
2. Validate the hub filter component

**Expected:**
Hub filter should be displayed like on the page  https://www.volvotrucks.us/news-and-stories/volvo-trucks-magazine/
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/227496199-aa7f3b27-5865-4da2-908f-1be95530a039.png">

**Actual:**
No Hub filter is being displayed
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/227496018-cd401583-42c0-4c62-a7b2-73a92b3e4554.png">

**Comment by rrusher** [comment]
This is addressed in https://github.com/hlxsites/vg-volvotrucks-us/pull/159.
