### ISSUE TITLE
form remote-programming/registration/

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#161]
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-programming/registration/

use iframe block https://github.com/hlxsites/vg-volvotrucks-us/issues/256 when ready. We can use fixed pixel height as a variant, to be verified that it's implemented. 

| iframe (4000px) |
|--------|
| https://survey.alchemer.com/s3/7102069/Volvo-Trucks-Uptime-Bundle-Preferences-Contacts?__ref=https%3A//www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-programming/registration/ |

**Comment by rrusher** [comment]
This is a survey from Alchemer (formerly SurveyGizmo).
It can be embedded: https://help.alchemer.com/help/javascript-embed

**Comment by synox** [comment]
I tried this, I failed with `Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.`

![Screenshot 2023-04-14 at 15 48 07](https://user-images.githubusercontent.com/2250964/232168150-1fce3f9b-7cc4-4177-bb12-425d9c275e45.png)

https://help.alchemer.com/help/iframe-embed could be an option, but I can't get the iframe height to be dynamic, cross origin.
