### ISSUE TITLE
Typography: Style headings according to style guide

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/vg-volvotrucks-us#166]
As discussed in slack:

- we style the headings according to https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/foundation-typography--page
- we use the text block to apply additional styles on default content (font family, center, and in the future different font sizes eventually)
- ~for the importer we should put the headings on the pages in `text (center)`, e.g on the trucks pages https://www.volvotrucks.us/trucks/vnr-electric/~ (template style: center will center all default content already)

**Comment by Buuhuu** [comment]
Are you referring to "Taking you Further ..."? This is currently an h2 iirc

The key facts are currently being worked on in https://github.com/hlxsites/vg-volvotrucks-us/issues/186. For the author the value and unit will be a bold text, the block will split them and style the value and unit accordingly. Those are not headings.

**Comment by Joesturbo** [comment]
Correct we are using the heading to make the sizing larger - in the current system we did not have a way to increase size easily without making a heading. I believe we can increase the size of the font to handle the size properly in the block?

**Comment by Buuhuu** [comment]
>  I believe we can increase the size of the font to handle the size properly in the block?

(non-semantic) changes to the layout in the source document are not taken into account on the page. there is clear separation of content and layout. Styles need to be set with CSS either globally (what is call default content, like h1, h2, h3, ...) or specifically in blocks. For the headings we should aim for consistency on the pages.

In the particular example of the key facts the style will be set in CSS, implied by making the value + unit bold. See for example 
- https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B439B3C90-92BA-4DDA-A70F-7E8B56917A87%7D&file=index.docx&action=default&mobileredirect=true 
- https://issue-186--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/

To support changing a single text / heading we added a "Text" block which supports modifiers for the font-size, e.g.:

|Text (xs)|
|---|
| extra small text |

But this cannot be nested into other blocks, for example columns.
