### ISSUE TITLE
Footer with gray background missing

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#171]
https://www.volvotrucks.us/our-difference/
https://www.volvotrucks.us/our-difference/safety/

<img width="1383" alt="Screenshot 2023-03-31 at 01 27 43" src="https://user-images.githubusercontent.com/2250964/229067639-69c19bd9-3646-480b-a67c-9a7e9617657f.png">

**Comment by girishdigrajkar** [comment]
Based on above comments please revisit the issue status.

**Comment by andreibalanescu** [comment]
I can see the gray background for the footer now. I feel like this can be closed.

**Comment by Buuhuu** [comment]
The work is not merged yet, the PR is still open and requires some changes.
