### ISSUE TITLE
Defect: Minimal - Navigation bar Mega menu (dropdown menu) for Trucks - Text font on Trucks and Powertrain icons has slightly different margins

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#175]
The text for Trucks and Powertrain icons in the Trucks dropdown menu has slightly different margins between one row of text and another.

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/ and click on the Trucks drodpown menu in the Navigation bar
2. Go to https://www.volvotrucks.us/ and click on the Trucks drodpown menu in the Navigation bar
3. Compare the  the text margin from one row of text to another on Volvo VNR icon for example and notice that the margin space between rows of text is slightly larger on the hlx.page

**Expected result**
See bottom half of the screenshot
![image (206)](https://user-images.githubusercontent.com/127409602/229151448-712302ce-0468-4d8c-8601-9aad3d4a17c7.png)

**Actual result**
see top half of the screenshot

![image (206)](https://user-images.githubusercontent.com/127409602/229151598-2efd4518-f1f9-4b58-854b-d6c1cb050063.png)

**Comment by KJohnsn** [comment]
Seeing a slightly different issue in the Services Dropdown whereas the spacing between the lines is inconsistent with what the spacing is on the Live site. I've attached a screen shot for reference.
![Services Dropdown](https://user-images.githubusercontent.com/126615590/231840715-3e80c50d-3d09-40bd-aa33-31aa9cbf4172.PNG)

**Comment by KJohnsn** [comment]
Also noticed that the image height in the news stories section in the Navigation Mega Dropdown is inconsistent. I have attached the screenshot for reference.
![News Stories](https://user-images.githubusercontent.com/126615590/231841824-2b362b1e-c610-4789-831a-f722907291ba.PNG)

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
