### ISSUE TITLE
Defect: Major - Hero block - Trucks: Volvo VNR Electric - Image on Hero block is smaller and cropped and Text and Button from it are misplaced in the center

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#181]
The Image of the Hero block on the Volvo VNR Electric Truck page is smaller and cropped and the Text and Button on the component are placed differently (more centered)

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/
2. Go to https://www.volvotrucks.us/trucks/vnr-electric/
3. Compare the Hero block component and Notice that, on the hlx.page, the Image is smaller and cropped and the Text and Button are centered while on the volvotrucks.us site they are aligned more to the left

**Expected result**
see right half of the screenshot

![image (209)](https://user-images.githubusercontent.com/127409602/229430535-a2b4aa7a-7067-460d-b88d-905dadd2bb72.png)

**Actual result**
see left half of the screenshot

![image (209)](https://user-images.githubusercontent.com/127409602/229430612-3136889c-bed0-490e-be0b-bf7668cb91a0.png)

**Comment by andreibalanescu** [comment]
The issue here is that we only use one type of Hero on HLX page, while there are several variations on live site. This is one of the variation, so most probably we'll need to add a style in order to reach the Expected results. Please let me know.

**Comment by Buuhuu** [comment]
We said that we want to normalise the hero blocks to be the same on all pages, the only exception is the hero video.

**Comment by girishdigrajkar** [comment]
Defect could be closed as post defect validation call it is marked as 'wont fix'.

**Comment by Andrei-Boiangiu** [comment]
closing as fixed. for font alignment issue please refer to point 01 in #215
