### ISSUE TITLE
Defect: Minor - Carousel - Trucks - Links on Carousel items is not in bold and right arrow is missing

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#189]
Link text on the Carousel items from the Volvo VNR Electric Truck page is not bolded and the right arrow is missing

**Steps to reproduce:**
01. Open https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/ and scroll down to Carousel block ( beneath Applications Solutions for you)
02. Open https://www.volvotrucks.us/trucks/vnr-electric/ and scroll down to Carousel block ( beneath Applications Solutions for you)
03. Compare and notice the link text styling and the arrow next to the link text

**Expected result**
Link text style should be bolded and have a right arrow - see right side of screenshot

![image (213)](https://user-images.githubusercontent.com/127409602/229527141-baffc138-0b35-4743-8208-9fd5cc4f9c3a.png)

**Actual result**
Link text style is not bolded and the right arrow is missing - see left side of screenshot

![image (213)](https://user-images.githubusercontent.com/127409602/229527265-664c0f78-189d-4ece-bf60-c265c91cb301.png)

**Comment by Andrei-Boiangiu** [comment]
**NOTE: This issue occurs on all Carousel blocks on all the Trucks pages**

![image (220)](https://user-images.githubusercontent.com/127409602/229808609-1313c995-cffb-4f4a-91d8-6f325a6988d7.png)
![image (221)](https://user-images.githubusercontent.com/127409602/229808658-e3a34caf-d69c-4568-9ace-849abb9d4ab7.png)

![image (222)](https://user-images.githubusercontent.com/127409602/229808723-ca958980-6aec-4a9a-8a74-03b2c820ba78.png)

![image (223)](https://user-images.githubusercontent.com/127409602/229808789-0aa015df-4eee-4542-bd20-cb0da3592f65.png)

![image (224)](https://user-images.githubusercontent.com/127409602/229808826-4f29e345-81df-41de-b36f-e144ea3f67b2.png)

**Comment by Buuhuu** [comment]
Fixed with #217

**Comment by Andrei-Boiangiu** [comment]
missing right arrow confirmed as fixed. for the text not being in bold please refer to issue #216
