### ISSUE TITLE
Defect: Critical - Image Text - Trucks: Volvo VNR Eelectric - Images from Image Text Grid 2 are missing the video play button overlay and video link, additionally font size for text is too large

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#198]
Video play button and video link is missing on the Image Text components on the Image Text Grid of the Volvo VNR Electric Truck page

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/ and scroll down to the Image Text Grid 2
2. Go to https://www.volvotrucks.us/trucks/vnr-electric/ and scroll down to the Image Text Grid 2 where there are images with play button overlay and video links
3. Notice that the Images from Image Text Grid 2 on the hlx.page do not have video button overlay and clicking on them will not open the videos
4. Additionally the font size of the Text on Image Text Grid 2 is too large

**Expected result**
Images from Image Text Grid 2 should include the video button overlay and clicking on them should open the correct video page
Font size on Text should be smaller

![image (215)](https://user-images.githubusercontent.com/127409602/229713330-9e716fdc-2a90-4b7b-b1bf-95b0ef022589.png)

**Actual result**
Video button overlay and video links are missing from the Images from Image Text Grid 2
Font size on Text is too large

![image (215)](https://user-images.githubusercontent.com/127409602/229713560-8c4e9d81-ec39-44d0-b93e-53228bd6b447.png)

**Comment by Andrei-Boiangiu** [comment]
Video button overlay also missing on Images from **Image Text grid** from Trucks -> Volvo VHD -> Features

https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/features/

https://www.volvotrucks.us/trucks/vhd/features/

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/127409602/230631703-71392f70-1029-4988-9ab2-3572adfa5795.png">

**Comment by andreibalanescu** [comment]
Video URLs are already added on those block components, so they needs to be integrated as well. Nothing else from content side.

**Comment by Andrei-Boiangiu** [comment]
Video overlays also missing from all items on Meet Your Volvo page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/meet-your-volvo/
https://www.volvotrucks.us/trucks/meet-your-volvo/

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231379445-f7094d9d-e3c1-4296-a24f-5ccec86e5e68.png">

**Comment by synox** [comment]
content was fixed meanwhile

**Comment by Andrei-Boiangiu** [comment]
partially fixed.  it is fixed on all the above pages **except** on Images from **Image Text grid** from **Trucks -> Volvo VHD -> Exterior**

https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vhd/exterior/

https://www.volvotrucks.us/trucks/vhd/exterior/

Reopening for the following

<img width="963" alt="image" src="https://user-images.githubusercontent.com/127409602/232796878-251b117a-a967-4c82-b2a9-a749351d91c6.png">

**Comment by Joesturbo** [comment]
This issue is resolved..

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
