### ISSUE TITLE
Defect: Critical - Tabbed Module - Trucks: Volvo VNR Electric - Tabbed Modules are not correctly functional; have buttons that don't work instead of tabs

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#199]
On the Volvo VNR Electric Trucks page - all the Tabbed Modules except the first one are not functional: instead of tabs they have buttons that do not work

**Steps to reproduce:**
01. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/ and scroll down to the second Tabbed Module block
02. Notice that all the Tabbed Modules on the page except for the first one ( second, third and forth one) have buttons instead of tabs to click
03. Click on one of the buttons
04. Notice that they dont work
05. Notice that all the content of individual tabs is just displayed on the page below the buttons

06. Go to https://www.volvotrucks.us/trucks/vnr-electric/ and scroll down to the second Tabbed Modules and notice how the Tabbed Modules and tabs work and function there

**Expected result**
Tabbed Modules should be correctly configured and functional as seen on https://www.volvotrucks.us/trucks/vnr-electric/ 

![image (219)](https://user-images.githubusercontent.com/127409602/229743157-aa653ae6-0550-4dc3-ae3a-70649abee8ef.png)

**Actual result**
Tabbed Modules on Volvo VNR Electric Truck page are not functional; instead of tabs they have buttons that do not work
![image (216)](https://user-images.githubusercontent.com/127409602/229742779-23fc6166-f132-4223-b27b-c13eade8f79f.png)

![image (217)](https://user-images.githubusercontent.com/127409602/229742847-15bea2f4-2308-4c2a-9a41-f59ab23b986f.png)

 
![image (218)](https://user-images.githubusercontent.com/127409602/229742891-636fbdf7-4b4a-4a05-8d84-901c1765ce47.png)

**Comment by Buuhuu** [comment]
The content was not imported at the time of testing, this working now as expected.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
