### ISSUE TITLE
Defect: Major: Hero image is cropped, text is not arranged in new line and 'ITorque' text is missing

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#202]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
2.  Validate the text, Hero image

Expected Vs Actual:
1. Hero image is not in full size
2. Text is not arranged in new line and 'ITorque' text is missing
3. Text is not in all capital letter format

![image](https://user-images.githubusercontent.com/125972657/229762855-dad604bc-f854-4c39-bd82-4fe0afb575ae.png)

**Comment by andreibalanescu** [comment]
This happens because at this point, we only have one type of Hero component developed, while there are several variations on the live site.

**Comment by synox** [comment]
duplicates https://github.com/hlxsites/vg-volvotrucks-us/issues/181

**Comment by girishdigrajkar** [comment]
agree to closure.
