### ISSUE TITLE
Defect: Minor - Carousel Slick Slider - Trucks: Volvo VNR: Specifications - Left and Right arrows are missing from the Carousel Slick Slider

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#205]
On Specifications tab of Volvo VNR Truck - the Carousel Slick Slider is missing the left and right arrows

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/trucks/vnr/specifications/ and scroll down to the Carousel Slick Slider
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/ and scroll down to the Carousel Slick Slider
3. Notice that the Slider has no Left and Right arrows on the hlx.page

**Expected result**
Slider should have Left and Right arrows

**Actual result**
Slider does not have left and Right arrows

![image (225)](https://user-images.githubusercontent.com/127409602/229824970-f4ef706a-103c-43c3-8d3c-ca93388f7941.png)

**NOTE:** This Left and Right arrows are only present on the Slider from the Specification page of the Volvo VNR Truck and **not** on the Sliders present on other Trucks Specifacations tabs. (so maybe they can be removed everywhere on the Sliders? )

**Comment by Lakshmishri** [comment]
As discussed on slack they are not needed 
<img width="496" alt="Screenshot 2023-04-12 at 16 33 35" src="https://user-images.githubusercontent.com/4208604/231491126-37854990-a51e-476a-b662-200ddd738d4f.png">
