### ISSUE TITLE
Defect: Major - All FONT SIZE differences

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#209]
Most of the Text and Titles on block components show differences in Font Styling. 
This ticket is created to encompass and document all differences regarding FONT SIZE on the hlx.page site ( https://main--vg-volvotrucks-us--hlxsites.hlx.page/ ) compared to the VolvoTrucks US live site ( https://www.volvotrucks.us/ ) that are to be ammended.

**Note: this ticket is to be updated in comments with subsequent areas in which the Font Size difference is detected**
_an example or two in screenshots might be included on each point_ 
and each point will be numbered 01 - 100... for reference

Font size is larger on hlx.page site on the following blocks 

01. Title and Text on all **Image Text** blocks
![image (226)](https://user-images.githubusercontent.com/127409602/230018704-35bf969c-cbdd-4892-a722-dddb034ed2ef.png)

02. Title on **Product Grid** block
![image (227)](https://user-images.githubusercontent.com/127409602/230019269-472769f7-ca1e-4b6d-b081-77dda111b262.png)

03. Title and Text on **Image Text - only text**
![image (228)](https://user-images.githubusercontent.com/127409602/230020252-cc7c41e2-697e-4761-aaf0-01985a0638f4.png)

04. Title and Text on **Content Container - Padding Container** 
![image (229)](https://user-images.githubusercontent.com/127409602/230021505-7375b761-f695-466f-8005-2b90ca11384f.png)

05. Title on **Product Carousel**
![image (230)](https://user-images.githubusercontent.com/127409602/230022218-880934d4-bf3a-459e-a2d4-c2046070ad29.png)

06. Title and Text on a **Generic Grid - Intro**
![image (231)](https://user-images.githubusercontent.com/127409602/230024556-3ab4560b-7cfd-4761-8699-ff27fb344e37.png)

07. Title and Text on a **News Article block**
<img width="1906" alt="image" src="https://user-images.githubusercontent.com/127409602/230111182-0ee4131e-23a9-42f6-b345-e88fcff4c4bc.png">

08. Title and Text on a **Padding Container**
<img width="953" alt="image" src="https://user-images.githubusercontent.com/127409602/230115155-9de1e5bf-334f-486a-b8bd-bfd0a436cb15.png">

09. Title and Text on the Collapsible buttons on the **Specification Table**
![image (232)](https://user-images.githubusercontent.com/127409602/230118188-cf8d6398-7f92-4c09-bf9b-ed374f3e45ad.png)

10. Title and Text on **Tabbed Module**
![image (233)](https://user-images.githubusercontent.com/127409602/230120010-15e7fff0-400b-4909-be0d-362071211967.png)

**Comment by girishdigrajkar** [comment]
11. Font differences:
![image](https://user-images.githubusercontent.com/125972657/230846605-cc8a9d69-ac2c-48cf-961c-218cf7d22747.png)

**Comment by girishdigrajkar** [comment]
12: font difference:
![image](https://user-images.githubusercontent.com/125972657/230847304-412106b0-4760-459f-a2fc-ef46739cdc38.png)

**Comment by girishdigrajkar** [comment]
13:font differences:
![image](https://user-images.githubusercontent.com/125972657/230847630-16a953c8-19d1-4ad6-a84b-9c862917b900.png)

**Comment by girishdigrajkar** [comment]
14:
![image](https://user-images.githubusercontent.com/125972657/230851185-597a94bc-43f2-454e-a1a9-68cf40089a0b.png)

**Comment by girishdigrajkar** [comment]
15: font difference:
![image](https://user-images.githubusercontent.com/125972657/230851734-6c28f6f6-932d-4d63-a13e-64b7ad98e2c9.png)

**Comment by girishdigrajkar** [comment]
16: font difference:
![image](https://user-images.githubusercontent.com/125972657/230852738-67a47754-849f-4284-bdb7-f9a732907c14.png)

**Comment by Andrei-Boiangiu** [comment]
17. Titles of **Tabbed Module block**, Title and Text on the tabs of the **Tabbed Module**

<img width="1888" alt="image" src="https://user-images.githubusercontent.com/127409602/230882520-4cd8b415-d4fb-4a07-a10c-1bfae10612de.png">

**Comment by girishdigrajkar** [comment]
**18:** Font difference noted in disclaimer text on turbo-compounding-calculator page as expected is 11px whereas, actual font is 16px:

![image](https://user-images.githubusercontent.com/125972657/230887058-e2101486-ee68-4f86-9600-57353ec10a6e.png)

**Comment by girishdigrajkar** [comment]
19: The ImageText block in powertrain> D11 page has font difference for title, text :

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/230891507-136e9ba9-4f6f-40c9-99e3-f2c71b5d1bdb.png">

**Comment by girishdigrajkar** [comment]
20: ImageTextGrid-3 block i.e. 'More About The D11' section has font differences in title and section text:

![image](https://user-images.githubusercontent.com/125972657/231172895-47c3cd81-b303-4e4b-a3a6-f140054411d7.png)

**Comment by girishdigrajkar** [comment]
21:  The imagetext block below hero image on powertrain/cummins-x15/ page has incorrect font sizes:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231208082-39560776-aea0-48bf-9869-c450aeb203f5.png">

**Comment by girishdigrajkar** [comment]
22: The font differences are observed on Image text component of powertrain/i-shift-transmission/ page

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231212380-6eed57b8-ff3e-4559-9164-d8db21c46e06.png">

**Comment by Andrei-Boiangiu** [comment]
23. Title, subtitles, text and **Accordion** / **Collapsible Accordion blocks** on Services: FAQ page

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/127409602/231708169-6eeb3a73-e1dd-42c6-be9a-46fd9d30f4cc.png">

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231708750-af928bd9-7700-45d7-8bd7-332209c1b7db.png">

**Comment by girishdigrajkar** [comment]
25: Noticed font size differences on  powertrain/i-shift-transmission/i-shift-severe-duty/  page:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/232021773-80efd3a5-89d5-439a-82b8-80af364c73d2.png">

**Comment by ZoeBeykirch** [comment]
I found this font size difference in one more place - in the News and Stories Magazines bottom of the articles in the Related Content section for the article titles as seen in the screen shots below. 
![image](https://user-images.githubusercontent.com/125895595/232898845-ea6eec2a-9c67-4212-92fe-9e01bbf85b94.png)
![image](https://user-images.githubusercontent.com/125895595/232899002-18b5a835-8276-4e64-9557-18eedecc7440.png)

**Comment by Andrei-Boiangiu** [comment]
closing this ticket as fixed for all the above points

for other any outstanding Font Size difference issues that impact the user experience considerably- a separate ticket will be created
