### ISSUE TITLE
Defect: Major - All TEXT ALIGNMENT differences 

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#215]
Most of the Text and Titles on block components show differences in alignment - text wrap - text positioning.
This ticket is created to encompass and document all differences regarding TEXT ALIGNMENT - text wrap - text positioning on the hlx.page site ( https://main--vg-volvotrucks-us--hlxsites.hlx.page/ ) compared to the VolvoTrucks US live site ( https://www.volvotrucks.us/ ) that are to be ammended.

**Note: this ticket is to be updated in comments with subsequent areas in which the TEXT ALIGNMENT - text wrap - text positioning difference is detected**
_an example or two in screenshots might be included on each point_
and each point will be numbered 01 - 100... for reference

see a similar ticket here for [FONT SIZE differences](https://github.com/hlxsites/vg-volvotrucks-us/issues/209)

01. Text and Button centered instead of aligned to the left on the **Hero Image block**
![image (234)](https://user-images.githubusercontent.com/127409602/230312906-6b568352-dd39-4bd6-969e-d415d86abd9d.png)

02. Subtite, Title, Text and Button on **Image Text block**
*NOTE:* in cases such as the screenshot below I would mark this as **Critical** from an user experience point of view. The white text being placed over the white background is not readable

 
![image (242)](https://user-images.githubusercontent.com/127409602/230394545-64cdde0d-d139-4161-a055-a204c4652c2c.png)

03. Slide caption text on **Tabbed Carousel block** should be wrapped
![image (249)](https://user-images.githubusercontent.com/127409602/230572995-f8be0a5d-d0cc-497a-8b24-3e46f888354d.png)

04. This particular Text formatting on this **Hero Image component**  https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/exterior/
_( I assume the idea is to have the truck clearly displayed in the image without it being covered by text )_

![image (252)](https://user-images.githubusercontent.com/127409602/230605848-6af115c8-2de7-4fd5-a754-0af734c92767.png)

05. Spacing between the lines on the **Three Column Specs block** ( ex:Trucks -> Volvo VNX -> Performance)

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/127409602/230627285-5ef94fa2-9112-4383-9893-24fa89ce129a.png">

06. Title on **Tabbed Module block** is not centered

![image](https://user-images.githubusercontent.com/127409602/230865407-48c44919-8ec6-4ddd-a7e0-e17f08b7ef12.png)

07. Links are differently aligned on the Tabs on the *Tabbed Module block*
 in this particular example below the alignment issue causes an incorrect overlap between the links 
  Parts -> Genuine -> Engine page, the Transmission Fluid tab on the Genuine Lubrication Tabbed module
   https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/genuine/engine/ 
   
    
![image](https://user-images.githubusercontent.com/127409602/230865938-5cf82e65-a0aa-424d-acdd-4b4008253fb0.png)

08. Title, Text and Link on the **News Article block**
 
<img width="1888" alt="image" src="https://user-images.githubusercontent.com/127409602/230910515-7e18b8e0-4e21-4439-bffb-f7c4e111c70d.png">

09. Text over Image on Services -> Uptime Service Solutions -> Remote Diagnostics page
 due to the Font / misalignment of Text over the image. the white text on the white background makes it barely readable thus creating a bad user experience.
 
<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231083838-08cd7a94-1acc-4477-af66-52f1fb940dcb.png">

10. This particular Text formatting issue on the **News Article block** from Services: Warranty page ( https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/warranty/ )

<img width="1820" alt="image" src="https://user-images.githubusercontent.com/127409602/231689498-5b3f78d9-d306-456a-8c7a-c5e41514ca41.png">

11. on **Subnavigation block** when resizing the window, wrapped text vs text going going on two rows - see screenshot below
  
  
<img width="1820" alt="image" src="https://user-images.githubusercontent.com/127409602/231701353-5ce0357c-2654-4b1b-9aa0-f6b2ee529ae7.png">

**Comment by girishdigrajkar** [comment]
12.  on powertrain/i-shift-transmission/i-shift-severe-duty/ page noticed text alignment issue :

![image](https://user-images.githubusercontent.com/125972657/232021396-641037cf-c2e5-471d-ae53-57307f1a0703.png)

**Comment by girishdigrajkar** [comment]
13: On https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/turbo-compounding-calculator/  text alignment issue observed:

![image](https://user-images.githubusercontent.com/125972657/232974121-ff221626-3b61-4a42-add5-834676bef511.png)

**Comment by Andrei-Boiangiu** [comment]
closing this ticket as fixed for all the above points

for other any outstanding Font Size difference issues that impact the user experience considerably- a separate ticket will be created
