### ISSUE TITLE
Defect: Minor - All other FONT STYLING issues and differences

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#216]
Several of the Text and Titles on block components show differences in **Font Styling**.
This ticket is created to encompass and document all differences regarding Font Styling on the hlx.page site ( https://main--vg-volvotrucks-us--hlxsites.hlx.page/ ) compared to the VolvoTrucks US live site ( https://www.volvotrucks.us/ ) that are to be ammended.

**Note that this does not include the differences regarding FONT SIZE or TEXT ALIGNMENT that which are documented separately in the two tickets below**

[Defect: Major - All FONT SIZE differences](https://github.com/hlxsites/vg-volvotrucks-us/issues/209)

[Defect: Major - All TEXT ALIGNMENT differences #215](https://github.com/hlxsites/vg-volvotrucks-us/issues/215)

**Note 2 : this ticket is to be updated in comments with subsequent areas in which the TEXT ALIGNMENT - text wrap - text positioning difference is detected**
_an example or two in screenshots might be included on each point_
and each point will be numbered 01 - 100... for reference

01. Text on **Button from Hero Image block** is not bolded
![image (235)](https://user-images.githubusercontent.com/127409602/230315301-d901246a-3c20-4a12-9987-6d077dafca43.png)

02. Subtitle Text on **Padding Container** is incorrectly in italic
![image (237)](https://user-images.githubusercontent.com/127409602/230324835-a02328ec-e2c9-4a71-a200-d474fa57dc61.png)

03. Subtitle Text on **Product Carousel block** is incorrectly in italic
![image (238)](https://user-images.githubusercontent.com/127409602/230326307-7ff267b4-44a5-4c82-b4cb-c5be304d6e5d.png)

04. Product Link Text on **Product Carousel Block** should be bolded and is missing right arrow
![image (239)](https://user-images.githubusercontent.com/127409602/230327707-09e8c69d-85ad-4c42-87cf-802f65f0687f.png)

05. Subtitle Text on **Image Text block* has incorrect color and styling
**NOTE:**: I mark this as **Critical** as it looks bad from an user experience point of view. The grey text on grey backgrounds is barely readable

![image (241)](https://user-images.githubusercontent.com/127409602/230389882-7f89a969-c3f0-48fe-bf60-3c7908a67416.png)

06. Text in Button from **Image Text block** is not bolded
![image (242)](https://user-images.githubusercontent.com/127409602/230398177-1c5f78bc-5be0-4e67-84a3-297484ef9bc1.png)

**Comment by girishdigrajkar** [comment]
7. The case is incorrect for below page:
![image](https://user-images.githubusercontent.com/125972657/230409083-74ab44af-8bfd-467b-a69c-580c1f2392ef.png)

**Comment by Andrei-Boiangiu** [comment]
08. Slide caption Text on **Tabbed Carousel** has different Font on name of the Truck

![image (248)](https://user-images.githubusercontent.com/127409602/230572659-d630be5a-79d7-4220-adb2-de58cd5b99ab.png)

**Comment by Andrei-Boiangiu** [comment]
10. Text on **Specification table** from Trucks: Features page should be in italic

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/127409602/230623313-f1070b4e-1385-4d19-a09f-f50d2b3aca85.png">

**Comment by girishdigrajkar** [comment]
11: Link text was expected to be bold :

![image](https://user-images.githubusercontent.com/125972657/230855340-37bfc147-4c00-453a-abac-6c211699a36b.png)

**Comment by Andrei-Boiangiu** [comment]
12. Link Text on the tabs from the **Tabbed Module** on Parts -> Genuine -> Page should should **not** be bolded or have the right arrow

<img width="1877" alt="image" src="https://user-images.githubusercontent.com/127409602/230867981-380f2be9-3681-4ffc-9ebd-d9587803a8cf.png">

additionally see this alignment issue causing an overlap and the second link to be cutout from the same Tabbed Module also mentioned in the ticket regarding Font Alignment

<img width="1877" alt="image" src="https://user-images.githubusercontent.com/127409602/230868191-bbe505bf-de05-4b52-8977-6130167ca6f6.png">

**Comment by girishdigrajkar** [comment]
13: The turbo-compounding-calculator page's hero image has text alignment incorrect.
  i.e. 'Calculating savings' follows the text unlike expected   &  both are not centrally aligned.

![image](https://user-images.githubusercontent.com/125972657/230884938-fb7b2458-24ce-4c96-93db-9b7a095dbb8f.png)

**Comment by girishdigrajkar** [comment]
14: Powertain > D11 > hero image has incorrect title text casing and background and title colour combination:

![image](https://user-images.githubusercontent.com/125972657/230889707-84482b02-f5bc-4b00-9631-4aef571251f0.png)

**Comment by girishdigrajkar** [comment]
15: The ImageText block in powertrain> D11 page has title with Italic styling whereas, expected is normal text.

![image](https://user-images.githubusercontent.com/125972657/230891937-c674f637-50f3-4b86-bf8c-04c520904f92.png)

**Comment by girishdigrajkar** [comment]
16: powertrain> D11 page has 360 view block with incorrect background than expected/earlier combination:

![image](https://user-images.githubusercontent.com/125972657/230894021-b9233fb6-8f16-4716-80a5-73bc29f6fd29.png)

**Comment by Andrei-Boiangiu** [comment]
17. Title on **News Article block** ( Parts -> Genuine -> Tranmsission) page should be in Caps Lock (besides alignment and font as noted in the other two issue tickets)

<img width="1888" alt="image" src="https://user-images.githubusercontent.com/127409602/230911019-c5effb3b-2124-482e-a56b-452869e931e4.png">

**Comment by Andrei-Boiangiu** [comment]
18. Text over **Image Text** (.us site) or **Teaser Card** (hlx.page site) on Services -> Uptime Service Solutions -> ASIST page
Gray and White text over white background causes the Text to be unreadable. I would mark it as a *Critical* from an user experience point of view

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231090584-35a88f36-5c3b-412c-b7eb-03bd022d4273.png">

**Comment by girishdigrajkar** [comment]
19:  powertrain/d13 has hero image with incorrect background colour

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231185871-73a405e0-2821-498a-b2b8-aa164bb98086.png">

**Comment by girishdigrajkar** [comment]
20:  powertrain/cummins-x15/ has hero image with incorrect background colour

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231207564-0b7e2bd4-6b86-4980-8f67-515ee680c155.png">

**Comment by girishdigrajkar** [comment]
22: Hero image on powertrain/i-shift-transmission/ page has incorrect background.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231211724-2372a6b6-d105-4493-ab06-da7650383bd4.png">

**Comment by girishdigrajkar** [comment]
24:  powertrain> i-shift-transmission page has 360 view block with incorrect background than expected/earlier combination:

![image](https://user-images.githubusercontent.com/125972657/231395940-c292aa6a-83dd-4be5-9adb-4b574abaebf0.png)

**Comment by girishdigrajkar** [comment]
25: powertrain> natural-gas page has 360 view block with incorrect background than expected/earlier combination:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231397059-2da26975-77f7-4bc6-adb2-ce730aab3e7b.png">

**Comment by Andrei-Boiangiu** [comment]
26. Title / text on **Document List block**

<img width="1820" alt="image" src="https://user-images.githubusercontent.com/127409602/231685828-9a030fbd-6919-43aa-bebe-fa9801b74ae2.png">

**Comment by Andrei-Boiangiu** [comment]
27. the **News Article block** on Services: Resources page
Title styling is different
Link is in bold with right arrow vs not bolded without right arrow

<img width="1867" alt="image" src="https://user-images.githubusercontent.com/127409602/231705718-7f69bc0a-cb8d-443c-ba54-3a888b6ce66b.png">

**Comment by Andrei-Boiangiu** [comment]
28. Title, subtitles, text and **Accordion** / **Collapsible Accordion blocks** on Services: FAQ page

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/127409602/231708169-6eeb3a73-e1dd-42c6-be9a-46fd9d30f4cc.png">

 
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231708583-4dee6288-0640-419e-afc4-36579c03e817.png">

**Comment by Andrei-Boiangiu** [comment]
29. Title and text on **Main Component block**  ( ex: About Volvo -> Our Difference page )

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/127409602/231775796-a6eca850-31d5-443d-8ee1-200dbf6d176e.png">

**Comment by KJohnsn** [comment]
Noticed this on the home page while scrolling down to the Driving Progress section,
![Driving Progress Live vs Staging](https://user-images.githubusercontent.com/126615590/231836294-4b271a80-cba3-4cbc-805f-e56ab409c3a8.PNG)

**Comment by girishdigrajkar** [comment]
31: When clicked on 'Play Episode' link present on https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/ page , the resulted page background is not as expected:

![image](https://user-images.githubusercontent.com/125972657/232981901-ab1c32cb-8199-43c9-8462-367e8ee89698.png)
