### ISSUE TITLE
Defect: Major - Hero Image block - Trucks: VNR Electric - Subtitle text is misplaced outside the Hero Image Block

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#218]
The Subtitle text on the Hero Image block is misplaced outside the block on the VNR Electric Truck page

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr-electric/ and see the Hero Image block
2. Go to https://www.volvotrucks.us/trucks/vnr-electric/ and see the Hero Image block
3. Notice that the Subtitle text "Charging Ahead" is misplaced outside the Hero Image component (and has different styling on text)

**Expected result**
Subtitle text should be inside Hero Image block - see right side of screenshot
![image (240)](https://user-images.githubusercontent.com/127409602/230344603-50af44d2-c160-4bd4-bb5b-ba60a9a41a44.png)

**Actual result**
Subtitle text is placed outside the Hero Image block - see left side of screenshot
![image (240)](https://user-images.githubusercontent.com/127409602/230344728-78d55e90-3a3e-4247-bd6e-9ee8ec41a04f.png)

**Comment by Andrei-Boiangiu** [comment]
fixed but it says "Chargin" instead of "Charging" 

cc @andreibalanescu  I guess this is a quick fix that can be tackled here?

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/127409602/231192378-63b024ba-1b2d-49e6-850a-2f57b7489d96.png">

**Comment by andreibalanescu** [comment]
Yes, indeed. It is fixed now and I guess ticket can be closed.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
