### ISSUE TITLE
Defect: Major: 'NEXT GENERATION D13TC' section has images instead of videos

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#222]
**Steps:**
1.  Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/
2. Validate the 'NEXT GENERATION D13TC' section has images instead of videos

**Expected Vs Actual:**
![image](https://user-images.githubusercontent.com/125972657/230405144-2209aabb-6089-4e94-81d1-8db32f98ae92.png)

**Comment by synox** [comment]
works now

**Comment by girishdigrajkar** [comment]
Hi @synox :
Validated now and the issue persists as the videos are displayed as image hence, reopening the defect:

![image](https://user-images.githubusercontent.com/125972657/232679719-dc9b450e-1ca1-4c3d-aa19-7dbaf165fc5b.png)

**Comment by synox** [comment]
Works in my Chrome browser, but reproduced in Firefox: 
```
failed to load module for video-link TypeError: selectedLink is undefined
    decorate https://main--vg-volvotrucks-us--hlxsites.hlx.page/blocks/video-link/video-link.js:9
    decorationComplete https://main--vg-volvotrucks-us--hlxsites.hlx.page/scripts/lib-franklin.js:374
[lib-franklin.js:378:21](https://main--vg-volvotrucks-us--hlxsites.hlx.page/scripts/lib-franklin.js)
```

**Comment by Buuhuu** [comment]
I added the missing fallback videos and hid the video link block when the the fallback link is missing.

**Comment by girishdigrajkar** [comment]
Validated and able to see the videos & are playing correctly hence, defect could be closed:

![image](https://user-images.githubusercontent.com/125972657/232757329-c40e4386-2a3b-4e04-929f-66766b825031.png)
