### ISSUE TITLE
Defect: Minor- Image Text block - Trucks: Volvo VNR - Learn More button is missing from VNR Truck Image Text block

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#228]
The Learn More button is missing from an Image Text block on the Volvo VNR Truck page

**Steps to reproduce:**
01. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/ and scroll down to the Image Text block beneath the Product Carousel
02. Go to https://www.volvotrucks.us/trucks/vnr/ and scroll down to the Image Text block beneath the Product Carousel
03. Notice the missing Learn More button

**Expected result**
Image Text block component should include the Learn more button with the right link

**Actual result**
Learn More button is missing from the Image Text block component on Volvo VNR Truck page

![image (251)](https://user-images.githubusercontent.com/127409602/230583972-6421df21-862e-4381-9a6b-b6e7d649ef04.png)

**Comment by Andrei-Boiangiu** [comment]
same issue on Volvo VNR - Exterior tab page

<img width="1866" alt="image" src="https://user-images.githubusercontent.com/127409602/230615030-bf90dbb3-1108-43a2-9b59-214f3e7d52ed.png">

**Comment by andreibalanescu** [comment]
Yes the expected results would be to remove the CTA from hlx page. I already done that, please check and let me know.

**Comment by Andrei-Boiangiu** [comment]
I can still see them on the hlx.page 
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/

<img width="1448" alt="image" src="https://user-images.githubusercontent.com/127409602/231772683-08d38015-7595-4e86-897d-4c5f2a764f12.png">

**Comment by Buuhuu** [comment]
removed the cta also on the /trucks/vnr/exterior/ page.

**Comment by andreibalanescu** [comment]
This has been fixed already. @Andrei-Boiangiu  please proceed with ticket closure. Thank you
