### ISSUE TITLE
Defect: Critical - Embedded Video - Trucks: Exterior tab and Interior tab - Embbedded YouTube videos + YouTube consent is missing from Trucks pages

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#230]
On the Exterior tab and the Interior Tab of the following Truck pages: Volvo VNR, Volvo VNL and Volvo VNX
- the Embedded Video with the Youtube consent are missing  / not configured yet

**Steps to reproduce:*
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/exterior/
2. Go to https://www.volvotrucks.us/trucks/vnr/exterior/
3. Notice the missing Embedded Video block + youtube consent

4. Same issue present on Interior and Exterior tabs pages for Volvo VNL and Volvo VNX trucks as well

**Expected result**
Embedded Video block with youtube consent should be correctly displayed and functional

**Actual result**
Embedded Video block + the youtube consent text are missing

![image (253)](https://user-images.githubusercontent.com/127409602/230609249-27df2f3e-4eeb-4c96-891d-95cf7d2cef0d.png)

**Comment by Andrei-Boiangiu** [comment]
same / similar issue occurs also on Services -> Uptime Service Solutions -> Remote Diagnostics page
black video holder is displayed instead of the Embedded Video + YouTube consent

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-diagnostics/
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-diagnostics/

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231081870-2c61524d-1014-42c3-81f9-11a5b8e7278d.png">

**Comment by Andrei-Boiangiu** [comment]
same issue on Services -> Uptime Service Solutions -> ASIST page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/service-management-platform-asist/
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/service-management-platform-asist/

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231089387-da28e865-466e-4e0e-beef-f5f35606967a.png">

**Comment by Andrei-Boiangiu** [comment]
Embedded videos are not present anywhere on the hlx.pages where they should be

**Comment by TomaszDziezykNetcentric** [comment]
@Andrei-Boiangiu 
I've created the PR which will add the low-resolution message for videos.
Regarding the not displaying video, please provide the fallback video. The `embed` block requires the local video link (the youtube link is optional).
If the video is not working (black rectangle) you should check if it is available. You can do that by opening the video link in the new tab. If it is not working you should reupload it (you can use the Franklin bot) and replace the link in the content. It is possible that links point to old video locations that don't exist anymore.

**Comment by Andrei-Boiangiu** [comment]
Embedded Videos are missing completely from some of the above mentioned pages

**Services -> Uptime Service Solutions -> Remote Diagnostics** page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-diagnostics/

https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-diagnostics/

<img width="1917" alt="image" src="https://user-images.githubusercontent.com/127409602/232798484-4f1a2b22-0676-49b6-8a11-d2e66e7e33dc.png">

**Services -> Uptime Service Solutions -> ASIST** page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/service-management-platform-asist/
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/service-management-platform-asist/


<img width="1917" alt="image" src="https://user-images.githubusercontent.com/127409602/232798836-cab3e921-b30d-42fc-bb61-33944085e0ca.png">

**Comment by Buuhuu** [comment]
I uploaded the videos and updated the embed block with the low res fallback videos. 

In the future, if there is an embedded video missing, please open the page's document and check if the embed block has the fallback video. If not, download it, upload it using the slack bot and update the embed block accordingly. If there are questions, always ask us in the channel. This is way faster than logging these kind of defects.

**Comment by Joesturbo** [comment]
This issue can be closed (content issue)
