### ISSUE TITLE
Defect: Minor - Tabbed Module - Trucks: Exterior: Volvo VNR and VNX - Title is missing from the Tabbed Module on Exterior tab

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#231]
On the Exterior tab for Volvo VNR and Volvo VNX Truck pages - the Title of the Tabbed Module blocks is missing

**Steps to reproduce:**
1. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/exterior/ and scroll down to the Tabbed Module (Tabs: Hood., Headlights..)
2. Go to https://www.volvotrucks.us/trucks/vnr/exterior/ and scroll down to the Tabbed Module (Tabs: Hood., Headlights..)
3. Notice that the Title for the Tabbed Module is missing

4. Same issue occurs also on the Volvo VNX Truck - Exterior page

**Expected result**
Title of the Tabbed Module should be present

**Actual result**
Title of the Tabbed Module is missing

![image (254)](https://user-images.githubusercontent.com/127409602/230613819-b0fc7c5e-8bc5-46f1-a657-79ac784e28bb.png)

![image (255)](https://user-images.githubusercontent.com/127409602/230613859-4dc4c884-43ca-4e14-8881-46e10cc33e25.png)

**Comment by Andrei-Boiangiu** [comment]
Title is also missing from the **Image Text Grid block** from Trucks -> Volvo VNX -> Performance tab

https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnx/performance/
https://www.volvotrucks.us/trucks/vnx/performance/

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/127409602/230629147-b96fb4d8-e1b6-4cdf-8f2f-04619afd79a9.png">

**Comment by Andrei-Boiangiu** [comment]
-The Title of the Tabbed Module on the Exterior tab  ( " Exterior Design " ) for VNR Truck page has been incorrectly placed inside the first tab instead of above the Tabs
 https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnr/exterior/
 
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231211958-966b0846-4cbe-4894-bdc1-9676e2c674be.png">


-Title of the Tabbed Module on the Exterior tab for VNX Truck page is still missing
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vnx/exterior/

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231212875-25588833-9844-42c4-978d-951a0c4ef2ac.png">

**Comment by andreibalanescu** [comment]
@Andrei-Boiangiu  all of those issues has been fixed. Please check and let me know.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
