### ISSUE TITLE
Defect: Major - Generic Grid block - Trucks: Volvo VAH: Features - Features is mispelled as "feautres" on the Image from the Generic Grid

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#233]
Feautres is mispelled as "feautres" on the Features subpage of the Volvo VAH Truck

**Steps to reproduce:**
01. Go to Trucks -> Volvo VAH -> Features
02. Notice the text on the third image of the Generic Grid block

**Note:** This is present on the volvotrucks.us page as well as the hlx.page
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/vah/
https://www.volvotrucks.us/trucks/vah/

**Expected result**
"Explore the VAH features"

**Actual result**
"Explore the VAH feautres"

<img width="1851" alt="image" src="https://user-images.githubusercontent.com/127409602/230633997-06bc3aed-3d85-4f64-ac5e-8afb274011de.png">

**Comment by andreibalanescu** [comment]
This has been done. Please check and let me know.
