### ISSUE TITLE
Defect: Major: The truck and button links are repeated under 'Availability' section & button is displayed instead of link

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#235]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/
2. validate the Availability section

Expected:
https://www.volvotrucks.us/trucks/powertrain/d13tc/
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/230854353-ab5691f1-6c79-4a7d-ad62-a61f38b1c9b2.png">

Actual:
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/
The truck and button links are repeated under 'Availability' section & button is displayed instead of link
![image](https://user-images.githubusercontent.com/125972657/230854762-03dd6962-5c59-4988-88f8-f6190633dc1e.png)

**Comment by andreibalanescu** [comment]
This has been done. Please check and let me know.

**Comment by girishdigrajkar** [comment]
@andreibalanescu : This is partially fixed as only one truck image is displayed now however, instead of link the button is displayed for 'VNL Series >' 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231709291-8d0a99a1-9e80-4359-9547-8d4d3268e858.png">

**Comment by synox** [comment]
This can be changed from a button to a link by making it italic. 
Feel free to directly edit the links when you see it being wrong.

**Comment by girishdigrajkar** [comment]
Validated and able to see correct results now hence, defect could be closed:

![image](https://user-images.githubusercontent.com/125972657/232758213-161f7f87-d922-443e-8d01-80bc770ac260.png)
