### ISSUE TITLE
Defect: Minor - Image Text block - Parts - There is a Button for Learn More on Image Text blocks from Parts page instead of URL text

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#236]
The Image Text blocks on the Parts page have a Button for "Learn More" instead of link text.

**Steps to reproduce:**
01. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/ and scroll down to Image Text grid
02. Go to https://www.volvotrucks.us/parts-and-services/parts/ and scroll down to Image Text grid
03. Notice the Learn More button vs link text

**Expected result**
See link text for Learn More on the right
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/127409602/230857007-b7693689-f00e-4cd9-a6ff-1992c59ff633.png">

**Actual result**
See button for Learn More on the left
<img width="1877" alt="image" src="https://user-images.githubusercontent.com/127409602/230857058-a6c772b4-6e5e-4336-b20c-1f572689c561.png">

**Comment by Andrei-Boiangiu** [comment]
same Issue occurs on **Three Columns block** from the Parts -> Genuine page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/genuine/
https://www.volvotrucks.us/parts-and-services/parts/genuine/

<img width="1877" alt="image" src="https://user-images.githubusercontent.com/127409602/230858406-62b83bf9-b9e4-48ea-8845-7682bbab44ac.png">

**Comment by Andrei-Boiangiu** [comment]
same issue present on **News Columns** for View I-Shift Product Guide button on Parts -> Genuine -> Transmissions page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/genuine/transmission/
https://www.volvotrucks.us/parts-and-services/parts/genuine/transmission/

 
<img width="1888" alt="image" src="https://user-images.githubusercontent.com/127409602/230911251-8458061e-0e80-4d87-86a0-d7bdb65eb19c.png">

**Comment by Andrei-Boiangiu** [comment]
Image text block on Parts: Uptime and Connectivity page

https://www.volvotrucks.us/our-difference/uptime-and-connectivity/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230928854-e3047ab1-1eac-432e-9416-250ded18311a.png">

**Comment by andreibalanescu** [comment]
Nothing to be done from content side, I feel like devs involvement is required here.

**Comment by Andrei-Boiangiu** [comment]
same on Services -> Fleets

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231729117-098fbc65-aff2-4b80-b5b8-8d0a873bc86c.png">
 

and on Services -> Fleets -> FleetsPreferred

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231728934-f3f64059-8df3-4ec8-8463-1d048fb0c357.png">

**Comment by andreibalanescu** [comment]
Thank you @jonatan-lledo-netcentric  ! I can confirm this has been fixed for all pages. 

@Andrei-Boiangiu  please check and proceed with ticket closure. Thank you
