### ISSUE TITLE
Defect: Minor: Title is missing in Hero image in case of turbo-compounding-calculator page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#237]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/turbo-compounding-calculator/
2. Validate the title of hero image 

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/230881388-038e15ce-5c9c-438b-adb1-560dc37857cf.png)

**Comment by andreibalanescu** [comment]
I was able to add the subtitle on its position, but not for the text. Is there something special I need to do here? Maybe our dev team can support

**Comment by andreibalanescu** [comment]
In this case, maybe we can go with option 2 for now.

**Comment by jonatan-lledo-netcentric** [comment]
so, in this case, this can be closed, isn't it?

**Comment by Andrei-Boiangiu** [comment]
closed as fixed as per above comment
