### ISSUE TITLE
Defect: Minor: The content container text is not within the image container block

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#238]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/turbo-compounding-calculator/
2. validate the image container of 'Contact a Dealer' section for title & text

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/230883424-dc9dd242-4f81-4708-9aec-4e6c3d57724b.png)

**Comment by andreibalanescu** [comment]
The container block is created accordingly here, but even thought, the text doesn't overlap the image yet. Can our devs take a look please?

**Comment by girishdigrajkar** [comment]
@andreibalanescu : Thanks for discussion on above comment and confirming the changes done;   changes are as expected hence, closing the defect.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231708292-1bde5a80-cb88-4c48-a951-08fbc6c5e89a.png">
