### ISSUE TITLE
Defect: Minor: The 'Download Brochure' button is not placed in the image container block 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#239]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d11/
2. Validate the The 'Download Brochure' button 

Actual:
The 'Download Brochure' button is not placed on hero image 

![image](https://user-images.githubusercontent.com/125972657/230888532-205f4a6c-93d0-48ac-88e1-27fe415da948.png)

**Comment by andreibalanescu** [comment]
This has been done. Please check and let me know.

**Comment by girishdigrajkar** [comment]
@andreibalanescu : able to see the button at correct place now, closing the defect

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231705708-0cd89f57-30dd-4f0d-98b0-3207e8b8b25a.png">
