### ISSUE TITLE
Defect: Major: Play Video icon/image is not displayed in imagetext block of powertrain/d11/  & d13 page 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#240]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d11/  or d13 page
2. Validate the play video icon

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/230890892-e53d6499-3462-44ae-8f7d-04a642583e5c.png)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231187612-344fc54b-99e8-4862-bd3a-100c83544582.png">

**Comment by synox** [comment]
content was fixed

**Comment by girishdigrajkar** [comment]
Validated and able to see correct changes so agree to defect closure:

![image](https://user-images.githubusercontent.com/125972657/232674364-f242c479-666a-44ee-9f07-15e8ed2e6d97.png)

![image](https://user-images.githubusercontent.com/125972657/232674382-dfb5d6f9-9f62-43e5-9a00-22e62ae5ae7d.png)
