### ISSUE TITLE
Defect:Minor : 360° VIEW title is missing from 360 view block on powertrain>D11 page & D13 page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#241]
Steps:
1. Navigate to the https://www.volvotrucks.us/trucks/powertrain/d11/  or  https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13/
2. Validate the title

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/230893545-d6e8e722-f90a-47a1-81ae-1583175ff24b.png)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231186998-d7d84e33-8b1c-4545-a21e-a3f6f7d677bd.png">

**Comment by andreibalanescu** [comment]
This has been done. Please check and let me know.

**Comment by girishdigrajkar** [comment]
@andreibalanescu :  Please see below and fix it :

**D11** : font is 36px instead of 24px
**D13** : Please fix it for D13 as well.


<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231704269-97c3c04c-c036-44db-97d5-2482dbe2256d.png">


<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231704719-6a641b52-a778-46ec-a27b-0d04f16b88e6.png">

**Comment by Buuhuu** [comment]
Added on both pages, made it h2 in both case. Difference in font-size expected / works as designed.
