### ISSUE TITLE
Defect: Major - Tabbed Module - Parts: Remanufactured: Engine - The Tabbed modules are not correctly configured on the Parts: Remanufactured: Engine page

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#242]
On the Parts -> Remanufactured -> Engine page, the Tabbed modules for the engines are not configured - instead of tabs there are buttons that do not work with the all the blocks displayed below

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/parts-and-services/parts/remanufactured/engine/ and see the Tabbed Module blocks for the engines
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/remanufactured/engine/ 
3. Notice that the content is not configured in the Tabbed Modules, instead of tabs there are buttons and all the blocks are displayed below instead of in tabs carousel

4. Click on the Buttons on the hlx.page
5. Notice that nothing happens

**Expected result**
Have the Tabbed modules blocks correctly configured as on the right side of the screenshots

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/127409602/230916937-96ce11d3-49df-4cd9-9789-d55f4d1775c3.png">

**Actual result**
The tabbed modules are not correctly configured, instead of tabs there are buttons that do not function displayed and all the blocks are displayed below

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/127409602/230918185-ce504792-2333-4299-b06f-12667cb33eee.png">

**Comment by girishdigrajkar** [comment]
Validated and able to see the tabbed module works correctly hence, closing the defect : 

![image](https://user-images.githubusercontent.com/125972657/232461433-f9821dd4-c71e-432a-b399-79d95b3dd026.png)
