### ISSUE TITLE
Defect: Major - News Article block - Parts: PartsASIST - There is URL text instead of Buttons on the News Article block for Learn More and Login

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#243]
On the News Article block from the Parts: PartsASIST page - Learn More and Login is URL text instead of buttons

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/parts-and-services/parts/partsasist/
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/parts/partsasist/
3. Notice that Learn More and Login from the News Article block are URL Text instead of buttons

**Expected result**
Learn More and Login should be buttons - see right side of the screen

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230924097-c23e4ee7-707b-4b9e-af51-9733c62cf4ba.png">

**Actual result**
Learn More and Login from the News Article block are URL text instead of buttons

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230924174-f08fc529-323c-4a88-bb3a-09e74850bf13.png">

**Comment by andreibalanescu** [comment]
I have tried to fix this but with no success. Maybe some devs can take a look please? Thank you, please let me know.

**Comment by Buuhuu** [comment]
Fixed this in the content

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed. although partially as it is not identical but looks better (than live even)

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/127409602/232699620-ebb2f2fe-535c-483a-8ec9-c0bdce9f72b0.png">
