### ISSUE TITLE
Defect: Major - Hero Image block - Uptime Service Solutions - Play Video button is incorrectly displayed outside of the Hero Image block

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#244]
On the Uptime Service Solutions page - the Play Video button is incorrectly displayed outside the Hero Image component

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/parts-and-services/services/uptime-service-solutions/
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/uptime-service-solutions/
3. Notice the Play Video button

**Expected result**
Play Video button should be correctly displayed within the Hero Image block

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230924961-34166e76-45cb-4cd9-8148-551b0883b1b4.png">

**Actual result**
Play Video button is incorrectly displayed outside of the Hero Image

**Comment by andreibalanescu** [comment]
This has been fixed. Please check and let me know
