### ISSUE TITLE
Defect: Minor - On Services: Uptime & Connectivity page, there is a Teaser card with Title, Text and Button over the Image instead of the Image Text block with the text, title, button below

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#246]
On the Services: Uptime & Connectivity page - there is a Teaser card blocl with the Title, Text and Learn More button over the Image instead of the Image Text block of the same content on the volvo trucks.us site with the Title, Text and Learn More button below

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/our-difference/uptime-and-connectivity/ and scroll down to the Remote Programming block 
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/ and scroll down to the Remote Programming block 
3. Notice that the Text, Title and Learn More button is over the Image instead of below the Image
4. Inspect and notice that on the hlx.page the block is a Teaser Card and that on the .us site the block is a Image Text block

**Expected result**
Block component should be an Image Text block with the Title, Text and Learn More below

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230931108-90af4838-6442-4ef0-a571-018204b7b8b6.png">

**Actual result**
Block component is a Teaser Card block with the Title, Text and Learn More button over the Image

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/230931139-6a2a6c66-b393-4a08-81b6-1b53880dd886.png">

**Comment by Andrei-Boiangiu** [comment]
similar issue of **Teaser Card** vs. **Image Text block* on Services -> Uptime Service Solutions -> Remote Diagnostics page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-diagnostics/
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-diagnostics/

but the text is over the Teaser card and the white text on white background makes it barely readable thus being Critical from an user experience point of view

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231084224-58ab2c16-1306-497a-b4bb-df9d40784042.png">

**Comment by Andrei-Boiangiu** [comment]
same issue as in the comment above (even more so) on Services -> Uptime Service Solutions -> ASIST page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/service-management-platform-asist/

https://www.volvotrucks.us/our-difference/uptime-and-connectivity/service-management-platform-asist/

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231091186-c1c268c1-5871-4887-a9dd-c2752809b8b4.png">

**Comment by andreibalanescu** [comment]
First issue from this ticket has been fixed. Regarding other comments, I feel like is more a FE task. From content side, the only workaround would be to have those images replaced. Please let me know

**Comment by synox** [comment]
- https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/service-management-platform-asist/
  - fixed by adding `(dark)`

- https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-diagnostics/
  - opened https://github.com/hlxsites/vg-volvotrucks-us/issues/316 to track separately
