### ISSUE TITLE
Defect: Critical - Video not displayed/ Video tag not supported on Remote Programming page

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#250]
On Services -> Uptime and Connectivity -> Remote Programming page - the video is missing from the hlx.page and it says "Your browser does not support the video tag."

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-programming/ and scroll down to the video (the second one below the Image Text blocks)
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-programming/ on the same browser and scroll down below the Image Text blocks 
3. Notice that the hlx.page the video is not displayed and it says "Your browser does not support the video tag)

**Expected result**
Video should be displayed correctly on the page

**Actual result**
Video is not displayed on hlx.page

<img width="1878" alt="image" src="https://user-images.githubusercontent.com/127409602/231098265-a134a335-4469-4610-8f60-163e98dac22a.png">

**Comment by girishdigrajkar** [comment]
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-shift-transmission/i-see/  page too has video tag issue:  
![image](https://user-images.githubusercontent.com/125972657/232002460-bd2735b1-5600-4812-9bd9-a58520618e04.png)

**Comment by Buuhuu** [comment]
@TomaszDziezykNetcentric does the embed support videos with only the local (no youtube) video?

**Comment by Buuhuu** [comment]
Fixed the content

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed for the above two cases
