### ISSUE TITLE
Defect: Major :  The text is missing in ImageTextGrid-3 block i.e. 'More About The D11' section  &  on AUTOMATION UPGRADED - SAVINGS DELIVERED section of/powertrain/i-shift-transmission/ page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#253]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d11/  or https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-shift-transmission/
2. validate the 'More About The D11' section 

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/231169594-4b7984fd-f0e5-422c-87b9-3b914bed1e7b.png)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231213985-9465273f-7825-4ea7-b6db-609c8e58daef.png">

**Comment by manuel-vara** [comment]
Content provided, @girishdigrajkar please verify is correct now.

**Comment by girishdigrajkar** [comment]
Thanks Manuel,  Validated now and able to see the missing content hence, closing the defect :
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/232378615-f8ab1641-0227-4538-9648-7e9818c126c2.png">
