### ISSUE TITLE
press releases: curated list

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/vg-volvotrucks-us#258]
Press releases list here:

https://www.volvotrucks.us/trucks/powertrain/i-torque/

**Comment by Buuhuu** [comment]
as discussed in the daily: the list is the 3 latest articles with the `Engines` tag

**Comment by girishdigrajkar** [comment]
@Buuhuu : Reopening the defect as Press releases section is empty in case of ITorque page:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/233069772-7409297d-c43b-4e62-bbb3-e950f1946c9b.png">

**Comment by Buuhuu** [comment]
@girishdigrajkar reindexing is done. We now have all the 317 PR in the list and on the i-torque you see the 3 latest with tag engines. I think that can be re-validated.

**Comment by girishdigrajkar** [comment]
@Buuhuu : Thanks for the update, able to see correct results and hence, agree to defect closure ... Thanks ....

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/233292270-4f59144e-3dc3-46cd-ad43-168cdbfe8b53.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/233292320-436afee2-f254-49e7-b7f2-b43e02739129.png">


<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/233292622-192212f0-fa59-48e4-8d9f-837ba1a44801.png">
