### ISSUE TITLE
Defect: Minor - Styling of Contact us Button on Service Tech Training is different

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#262]
On Services -> Training -> Service Tech Training page, the Styling of the button is different

**Steps to reproduce:*
01. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/training/service-tech-training/ and scroll down to the Contact Us button
02. Go to https://www.volvotrucks.us/parts-and-services/training/service-tech-training/ and scroll down to the Contact Us button
03. Notice the styling difference

**Expected result**
see left side of screenshot

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231386978-d5556938-70ef-4400-b32a-26ee847530d0.png">

**Actual result**
see right side of screenshot

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231387044-31b04256-10c7-414e-a9a2-86b8da88debf.png">

**Comment by andreibalanescu** [comment]
This is already setup as left-aligned but with no changes. I have the same issue on other tickets, or when is about to make a certain text, centered. Maybe our devs can have a look please?

**Comment by synox** [comment]
looks good now.
