### ISSUE TITLE
Defect: Critical - Body Builder Support page - Body Builder Support page is not correctly configured / has different blocks

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#263]
The Body Builder Support page on hlx.page ( https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/ ) is not correctly configured and has different / missing blocks compared to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/

**Steps to reproduce:**
01. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/
02. Go to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/
03. Notice how differently the pages are configured

**Expected result**
Body Builder Support page should be correctly configured

**Actual result**
Body Builder Support page is not correctly configured

**NOTE:** it is unclear to me if this defect is related with this item that is currently open at the time of logging this ticket block: body builder news #234 , if that is the case then this ticket can be closed as invalid

**Comment by Joesturbo** [comment]
This can be closed - a content tweak could be made to the page but good enough for launch.
