### ISSUE TITLE
Defect: Major - Image Text only text block - Services: Body Builder Support: FAQs page - Request Custom Drawing Image Text block is missing text

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#264]
On the FAQs page of Services: Body Builder Support - the Image Text (only text) block is missing text

**Steps to reproduce:**
01. Go to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/faqs/ and scroll down until Request Custom Drawing Image Text block
02. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/faqs/ and scroll down until Request Custom Drawing Image Text block
03. Notice that the text is missing from the Image Text block and also the link styling is different

**Expected result** 
block should contain text informing the user how to request the custom PDF drawing and the link styling should be different
see right side of screenshot

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231392078-ffce63c9-7b23-42a1-94d9-ebc5c581e878.png">

**Actual result**
block is missing text informing the user how to Request custom drawing and link styling differes
see left side of screenshot

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231392245-edc6b5a4-ec8c-4200-b81e-34e7ab5e1ad9.png">

**Comment by Andrei-Boiangiu** [comment]
same issue occurs on Body Builder Support: Training page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/training/
https://www.volvotrucks.us/parts-and-services/services/body-builder-support/training/

**Comment by Joesturbo** [comment]
Done!
