### ISSUE TITLE
Defect: Major - Services: Body Builder Support: FAQs page - News & Events title and link is missing from Body Builder Support: FAQs page and an additional paragraph of text is displayed

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#265]
On the FAQs page of Services: Body Builder Support - the title and link for News & Events is missing from the page and an additional two paragraphs of text are displayed instead

**Steps to reproduce:**
01. Go to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/faqs/ and scroll down to News & Events
02. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/faqs/ and scroll down to News & Events
03. Notice that the title and link from News & Events is missing from the page and an additional two paragraphs of text are displayed instead

**Expected result**
News & Events title and link should be included on the page and the two paragraphs of text on Volvo Trucks North America should be removed
see right side of the screenshot
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231394676-b66edbd3-1224-43a8-8617-daa572be5c20.png">

**Actual result**
News & Events title and link are missing on the page and two paragraphs of text are displayed there
see left side of the screenshot

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231394902-dbcb1325-7eb6-4e8a-839c-fe9fbd324543.png">

**Comment by Andrei-Boiangiu** [comment]
same issue occurs on Body Builder Support: Manuals page

https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/manuals/
https://www.volvotrucks.us/parts-and-services/services/body-builder-support/manuals/

**Comment by synox** [comment]
looks good to me, please verify again
