### ISSUE TITLE
Defect: Critical - Document List block - Services: Body Builder Support: Manuals - Document List block is not correctly configured and Disclaimer text is missing

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#267]
On the Services -> Body Builder Support -> Manuals page - the Document List block is not correctly configured and also the Disclaimer text above it is missing and there are some other paragraphs of text instead

**Steps to reproduce:**
01. Go to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/manuals/
02. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/manuals/
03. Notice that the Document list blocks are not correctly configured and that the Disclaimer text above it is missing and there is other paragraph of text there instead

**Expected result**
Document List blocks should be correctly added/configured and the Disclaimer text should be present above it 

**Actual result**
Document List blocks are not correctly configured and the Disclaimer text is missing and there are other paragraphs instead

<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231409056-36e00776-8a17-42ca-b611-55a7f3200e3d.png">

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed

**Comment by Joesturbo** [comment]
All good!
