### ISSUE TITLE
Defect: Minor - Services: Body Builder Support: Tools - There is a small "null" paragraph on the page

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#268]
On Services -> Body Builder Support -> Tools - there is a small "null" paragraph on the page

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/parts-and-services/services/body-builder-support/tools/
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/tools/
3. Notice that there is a small "null" paragraph on the page below the first image

**Expected result**
Remove "null" paragraphs

**Actual result**
There is a small "null" paragraph on the page
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/127409602/231422194-266e9155-8fe0-4515-b8c0-dfbeec2130b3.png">

**Comment by andreibalanescu** [comment]
Hi @Andrei-Boiangiu , I'm not able to replicate this. What browser do you use?
