### ISSUE TITLE
Defect: Critical: Calculator - Results section i.e. tcc promo-text-box results block is not displayed correctly

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#271]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/d13tc/turbo-compounding-calculator/
2. Validate the Results section

Expected vs Actual:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/231479188-d482e964-2242-422b-aaa5-c6ce245908c4.png">

**Comment by synox** [comment]
duplicates https://github.com/hlxsites/vg-volvotrucks-us/issues/50

**Comment by Buuhuu** [comment]
fixed with #310

**Comment by Joesturbo** [comment]
This is resolved with new design

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
