### ISSUE TITLE
Defect: Major: The volvo-turbo-calculator-form is incorrect on the powertrain/d13tc/turbo-compounding-calculator/ page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#273]
Steps:
1. Navigate to https://www.volvotrucks.us/trucks/powertrain/d13tc/turbo-compounding-calculator/
2. Validate the volvo-turbo-calculator-form

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/231489555-241ea761-661b-49cb-8545-a677e067e57e.png)

**Comment by synox** [comment]
@dkuntze this is about the form, not the calculator. 


@girishdigrajkar The form has been fixed.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
