### ISSUE TITLE
discussion: how to manage center/left align with sub-pages

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#275]
Most pages are center-aligned, so let's make that the default. Using metadata.xlsx does not really work. 

Let's make center the default, and add left-align to the pages (in the word document's metadata) instead of the metadata.xlsx. 

e.g.. currently `/parts-and-services/**` is marked as `center`, but https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/news-and-events/expanded-body-builder-support/ should be left-aligned. with metadata.xlsx we don't have any option to make this exception.

**Comment by synox** [comment]
@dkuntze @Buuhuu please review the proposal.

**Comment by dkuntze** [comment]
Why doesn't metadata work?

**Comment by Buuhuu** [comment]
> but https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/body-builder-support/news-and-events/expanded-body-builder-support/ should be left-aligned. with metadata.xlsx we don't have any option to make this exception.

Just add `Style: left` to the page. It works. 

> Most pages are center-aligned, so let's make that the default. 

Not sure about "most pages". A lot of pages are press releases and they are left aligned.

**Comment by synox** [comment]
thanks for the feedback. For some reason metadata.xlsx did not work when I had a top-level `/**` setting for `center` and then single page override for `left`. I'll try again.

**Comment by synox** [comment]
here is an example: 
 
| /parts-and-services/services/body-builder-support/**   | | center |  
-- | -- | -- | --
/parts-and-services/services/body-builder-support/news-and-events/**   |   | left |  
/parts-and-services/services/body-builder-support/training/   |   | left |  

For `/parts-and-services/services/body-builder-support/training/` the `center` is still applied, even if I define `left` for it. 
I guess I would have to remove `/parts-and-services/services/body-builder-support/**` and add one for each child? That gets too messy quickly.

**Comment by Buuhuu** [comment]
For individual pages, better set the metdata directly on the page. I did so on `/parts-and-services/services/body-builder-support/training/` and that works. Not sure if the `index.docx` cause this.

For `/parts-and-services/services/body-builder-support/news-and-events/**` left is applied correctly afaics.
