### ISSUE TITLE
Defect: Minor - Image Text blocks - FleetsPreferred page - Image Text blocks are all arranged with image on left and text on right 

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#282]
On the FleetsPreferred page on the hlx.page - the Image Text blocks are all arrange with image on left and text on the right while on the volvotrucks.us site they alternate (first block has image on left and text on right, next block has text on left and image on right etc)

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/parts-and-services/fleets/fleetpreferred/ and check the Image Text blocks
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/fleets/fleetpreferred/ and check the Image Text blocks
3. Notice the way the images and text are arranged

**Expected result**
The position of Image and Text on Image Text blocks should alternate: first block with image on the left and text on the right, second block with text on the left and image on the right etc

**Actual result**
All Image Text blocks are arranged with Image on left and Text on right

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231758010-11cf5420-6814-40ea-bd53-5b29615b40fe.png">

<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231758165-c7f2b263-09e5-4e49-95da-83574bda89d0.png">

**Comment by dkuntze** [comment]
@Joesturbo fixed and published.
