### ISSUE TITLE
Defect: Major - Hero Component block - About Volvo: Our Difference - Text on Hero and Title below are misplaced

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#284]
The Hero Component block on the About Volvo: Our Difference page has the text and title below misplaced 
on https://www.volvotrucks.us/our-difference/: Text on the Hero component is "WHY VOLVO" and Title below is "DRIVING PROGGRESS. IT'S OUR PROMISE."
while on https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/ these are reversed: Text on the Hero component is "DRIVING PROGGRESS. IT'S OUR PROMISE." and the Title below is "Why Volvo"

**Steps to reproduce:**
1. Go to https://www.volvotrucks.us/our-difference/ and notice the Hero component and the title below
2. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/ and notice the Hero component and the title below
3. Notice the text over the Hero component and the title below

**Expected result**
see right side of the screenshot
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231762649-bd474952-cf0f-471b-a397-59c7f356d8e4.png">

**Actual result**
see left side of the screenshot
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/127409602/231762597-96c372d8-de4b-4bf2-b46a-6ed3b7982f02.png">

**Comment by Joesturbo** [comment]
This can be closed....
