### ISSUE TITLE
Defect: Minor: [Mobile/Iphone SE/Samsung S8+] The imageTextGrid-description is missing in case of 'In The News' section

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#288]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/
2. Validate the imageTextGrid-description  of the 'In The News' section

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/231780743-7cdfd08d-5762-4632-b84f-421138299db7.png)

**Comment by dkuntze** [comment]
added the missing text. published
