### ISSUE TITLE
Defect: Major: [Mobile/Iphone SE/Samsung S8+] The 'Play Episode' links in the 'In The News' section are not configured. (Soundcloud)

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#289]
Steps:
 1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-torque/   page in responsive mode for IphoneSE view
 2.  Validate the links in 'In The News' section

Expected vs Actual:
![image](https://user-images.githubusercontent.com/125972657/231785083-1df8ee55-b5ad-4807-95c5-13f0823c1230.png)

**Comment by andreibalanescu** [comment]
I can confirm this is fixed now. @girishdigrajkar  please check and continue with ticket closure.

**Comment by Buuhuu** [comment]
Fixed with #312

**Comment by girishdigrajkar** [comment]
Agree with the defect closure as able to get correct results.
