### ISSUE TITLE
Defect: Body text not left aligned 

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-volvotrucks-us#292]
On this page: https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/reman-center/

The text in word is selected to be left justified - however it displays as centered.

**Comment by dkuntze** [comment]
@Joesturbo can you validate and close?

**Comment by andreibalanescu** [comment]
From content perspective the text is aligned properly now. Once confirmed, ticket can be closed.
