### ISSUE TITLE
Defect: CTA link in hero does not open in new window

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-volvotrucks-us#293]
CTA does not have the ability to "open in new window" to take people away from site: https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/reman-center/

**Comment by Buuhuu** [comment]
- all external origins open in new tab
- all pdfs open in new tab

**Comment by Joesturbo** [comment]
closed all good!

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
