### ISSUE TITLE
Defect: Diagnostic Tools Comparison downloadable PDF link and file are missing

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#294]
**URL**
https://main--vg-volvotrucks-us--hlxsites.hlx.page/parts-and-services/services/uptime-service-solutions/diagnostic-tools/

**Description**
On the Diagnostic Tools page, there is a Diagnostic Tools table which, on the current live site, has a link to a downloadable PDF. On the staging version of the site, the link and the PDF are both missing.

**Screenshots**
Without the link and the PDF
![Diagnostic Tools PDF Missing](https://user-images.githubusercontent.com/126615590/231860153-535ded28-9537-4f2a-8373-a5e78224e1ea.PNG)

Live site with the link to the PDF
![Diagnostic Tools With PDF Link](https://user-images.githubusercontent.com/126615590/231860179-00b1b8ad-467f-4949-9a25-bf33964d2642.PNG)

**Comment by synox** [comment]
fixed

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
