### ISSUE TITLE
Defect: minor: Hero image has title missing & sequence of content is incorrect on powertrain/i-shift-transmission/i-shift-severe-duty/ page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#295]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/powertrain/i-shift-transmission/i-shift-severe-duty/
2. Validate the sequence of content, missing text 

Expected vs Actual:

![image](https://user-images.githubusercontent.com/125972657/232019602-d86b30d6-8e46-4cf7-9886-bddb55db3d92.png)

**Comment by synox** [comment]
fixed

**Comment by girishdigrajkar** [comment]
Validated and able to see correct result hence, closing the defect now.

![image](https://user-images.githubusercontent.com/125972657/232395735-35bb3d2b-22be-42cd-880f-2851faac0fbe.png)
