### ISSUE TITLE
commit elq forms - adjust content where needed

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/vg-volvotrucks-us#297]
[Forms.zip](https://github.com/hlxsites/vg-volvotrucks-us/files/11233788/Forms.zip)

Use the elqFormName as name of the html file in GH.

**Comment by rrusher** [comment]
[297-eloqua-forms](https://github.com/hlxsites/vg-volvotrucks-us/pull/303) resolved this issue.

**Comment by rrusher** [comment]
https://github.com/hlxsites/vg-volvotrucks-us/pull/303 resolved this issue.
