### ISSUE TITLE
Defect: Double CTAs in the Header

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#300]
**URL**
https://main--vg-volvotrucks-us--hlxsites.hlx.page/about-volvo/facilities/powertrain-facility/

**Description**
On the Powertrain landing page, there are 2 CTAs in the header. Expected behavior is that there is only one CTA instead of 2.

<img width="557" alt="Double Directions CTA" src="https://user-images.githubusercontent.com/126615590/232088675-5e32f40d-a01a-4a91-818d-66fb00b6a500.PNG">

**Comment by Buuhuu** [comment]
@synox please close that after reverting #249
