### ISSUE TITLE
Teaser images sizes on the volvo-dynamic-steering page is not consistent

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-volvotrucks-us#305]
The teaser images for "CROSS-WIND" and "EASE-OF-BACKING" appears to be small compared with the other teaser images on the page.
https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/driver-productivity/volvo-dynamic-steering/

**Comment by Buuhuu** [comment]
The originals are too small. We usually do not recommend to upscale images. Do you have them in a higher resolution and could you update the content?

**Comment by andreibalanescu** [comment]
I can make the update if I'll get the proper images
