### ISSUE TITLE
Defect: Major: The 'USA' link within link list in Header block results in 404 page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#318]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/
2. Click on the 'USA' link within link list in Header block
Expected:
![image](https://user-images.githubusercontent.com/125972657/232755525-2ef032b9-7fc5-4e81-b10e-efca369a24e6.png)

Actual:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/232755694-e6035384-bd4b-415c-ba8f-daef9689863e.png">

**Comment by Buuhuu** [comment]
I cannot follow the steps. If I go to  https://main--vg-volvotrucks-us--hlxsites.hlx.page/ I get the homepage. If I go to https://www.volvotrucks.com/en-en/select-market.html and select North America > US > English I get the homepage too.

**Comment by Buuhuu** [comment]
I changed the link in the `nav` document. You have to flush your browser cache to make it work for you. 

Next time, for that kind of issues, feel free to adjust the content yourself (and ask in the channel if you don't know where exactly). Logging that kind of defects takes a magnitude longer than fixing.

**Comment by girishdigrajkar** [comment]
Validated and able to navigate to correct page hence, closing the defect.
