### ISSUE TITLE
Defect: Page styling breaks after minor edits in Volvo Trucks Magazine Article

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#322]
**URL**
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/denney-story/

**Description**
When going in to tidy up the page using Adobe Franklin's Google Extension Sidekick, I edited a few sub headers to make them bold but when I previewed the changed, the page formatting was broken.

**Screenshot**
<img width="738" alt="Page broken 1" src="https://user-images.githubusercontent.com/126615590/232797532-a5ec1e2d-5183-41ff-a6c4-8fcbdeca7dcd.PNG">
<img width="661" alt="Page broken 2" src="https://user-images.githubusercontent.com/126615590/232797537-9641fc67-832a-4a3b-870f-57127261f9be.PNG">
<img width="659" alt="Page broken 3" src="https://user-images.githubusercontent.com/126615590/232797549-58fedf11-ae7b-4375-bf7e-4f132b0caa67.PNG">
<img width="683" alt="Page broken 4" src="https://user-images.githubusercontent.com/126615590/232797554-0603e540-97c0-462e-8f7f-72457e16809f.PNG">
<img width="570" alt="Page broken 6" src="https://user-images.githubusercontent.com/126615590/232797557-a6341ee2-9d94-4cf4-b406-af3257129e6a.PNG">
<img width="715" alt="Part broken 5" src="https://user-images.githubusercontent.com/126615590/232797558-6b124915-d9d5-4c05-af46-e9a33896d919.PNG">

**Comment by ZoeBeykirch** [comment]
I also tried to restore a version history to yesterday, and this did not resolve the issue.

**Comment by rrusher** [comment]
Branch merged in that resolved the issue.
