### ISSUE TITLE
Defect: Videos are automatically downloaded instead of being viewed in the video player

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#331]
**URL**
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/meet-your-volvo/

**Browser:** Chrome

**Description**
When I view the videos in the teaser cards, there are some videos which prompt downloading them instead of them appearing in the pop-up video player. The teasers which are prompting the downloads are:

- Driver Environment on the VNR Electric
- Driving the VNR Electric
- Charging the VNR Electric
- Driver walkaround of the VNR Electric

**Screenshots**
<img width="852" alt="Video player issue" src="https://user-images.githubusercontent.com/126615590/232865539-82e34599-40d8-4748-a014-6c086bb7f846.PNG">

**Comment by rrusher** [comment]
The MP4s that play correctly have `Content-Type: video/mp4` in the header.
The MP4s that download have something else, like `Content-Type: application/octet-stream` in the header.

**Comment by Andrei-Boiangiu** [comment]
**Driver Environment on the VNR Electric** plays correctly

this issue occurs for:

Driving the VNR Electric
Charging the VNR Electric
Driver walkaround of the VNR Electric

**Comment by dkuntze** [comment]
I think this page is built wrong for videos - it really should be <video> tags that can define content type on the page. When using <a> tags, you are at the mercy of what the server responds with.

**Comment by synox** [comment]
This is not related to the `<a>`, but the use of `iframe`. As soon as `<iframe frameborder="0" allowfullscreen="allowfullscreen" src="https://www.volvotrucks.us/media_1f1e280ed2710daa4ac55d007e9ad6454b871aba5.mp4" class="modal-video"></iframe>` is added to the document, the file is downloaded. 
`<video>` is a good idea I will check.

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
