### ISSUE TITLE
Defect: Minor - Missing "Related Content" Title at bottom of Magazine Articles 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#333]
The title for "Related Content" at the bottom of the magazine articles is missing on each page. See example screen shots below. 

![image](https://user-images.githubusercontent.com/125895595/232900360-e534a33a-2416-4fe9-b3ef-69d3fa9bf13f.png)
![image](https://user-images.githubusercontent.com/125895595/232900480-74e747a7-5fe1-4e78-ac20-e9f59ceae5a7.png)

Additionally, some magazine article pages are missing this title and block all together for related content to be shown at the bottom: 
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/cover-story-great-expectations/ 
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/denney-story/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/business-story-walking-the-walk/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/tech-in-focus-on-the-road-with-i-torque/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/the-assignment-no-limits/

**Comment by rrusher** [comment]
Added the missing title during the import. All magazine articles, once published will have the title.
