### ISSUE TITLE
[Critical] Image is not automatically linked, url visible below image 

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#337]
https://main--vg-volvotrucks-us--hlxsites.hlx.page/trucks/
https://www.volvotrucks.us/trucks/

![Screenshot 2023-04-18 at 19 25 32](https://user-images.githubusercontent.com/2250964/232950477-556be8cc-dfdb-4abc-9cae-95177353fd2f.png)

**Comment by Buuhuu** [comment]
This is a content issue. To link the image the link href pathname must equal the pathname of the text content url: https://github.com/hlxsites/vg-volvotrucks-us/blob/main/scripts/scripts.js#L244-L251. Someone updated the hrefs but not the link text. 

Why did we implement a filter it like that
