### ISSUE TITLE
Defect: Major - iFrame - Mobile View - iPhone SE / Android - Longer text fields are not correctly / incompletely displayed

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#347]
On the Uptime & Connectivity Register page ( iFrame) - the longer text fields are incorrectly displayed in Mobile view
**About Volvo -> Uptime and Connectivity -> Remote Programming -> Uptime Preferences & Contacts**

**Steps to reproduce:**
1. Open https://main--vg-volvotrucks-us--hlxsites.hlx.page/our-difference/uptime-and-connectivity/remote-programming/registration/ on Mobile view
2. Open https://www.volvotrucks.us/our-difference/uptime-and-connectivity/remote-programming/registration/ on Mobile view
3. Compare and notice that some of the longer text fields appear cutoff and incomplete

**Expected result**
Text fields should be correctly displayed and wrapped within frame - see right side of screenshot
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/127409602/233074980-8a47e615-f418-484e-8814-4b62b5e83b89.png">

**Actual result**
Text fields are incorrectly displayed and cutoff - see left side of screenshot
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/127409602/233075086-9df191c9-c928-4609-a2d2-8c5ac347462a.png">

**Comment by rrusher** [comment]
This form is managed by the provider, Alchemer.
The size on these Input fields is set to 50, which is why it is cutoff on smaller screens.
The same for the TextArea, its' cols is set to 50.

I recommend changing the form at the source.
