### ISSUE TITLE
Defect: Major - Form in modal sidebar - Text on Offer form displays an expired date

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#354]
the modal sidebar on Get an offer button ( **Purchasing a Truck -> Financing -> Get this Offer button** ) displays an expired offer "Offer expires on December 30, 2022" instead of "December 29, 2023"

**Steps to reproduce:**
01. Go to https://www.volvotrucks.us/purchasing-a-truck/financing/ and click on one of the Get this Offer buttons
02. Go to https://main--vg-volvotrucks-us--hlxsites.hlx.page/purchasing-a-truck/financing/ and click on one of the Get this Offer buttons
03. Notice the text on top of the form

**Expected result**
Text on form should not display the expired date - see right side of screenshot

<img width="1891" alt="image" src="https://user-images.githubusercontent.com/127409602/233319144-2f9959da-010f-4b24-ba80-bb525d176182.png">

**Actual result**
Text on form displays an expired date - see left side of the screenshot

<img width="1891" alt="image" src="https://user-images.githubusercontent.com/127409602/233319308-7c6eb7a4-ecf1-47d6-be65-77f5f9b31ea9.png">

**Comment by Buuhuu** [comment]
That is a content issue. I updated the expiration date of the offers on the page and in the sidebar(s). I also merged the 3 columns blocks into one and configured it so that it stacks with the images coming before the text on mobile viewports.
