### ISSUE TITLE
Import /trucks/calendar/

### ISSUE THREAD

**Issue by synox** [hlxsites/vg-volvotrucks-us#364]
https://us.vtnaprod-cm.na.volvogroup.com/trucks/calendar/
on https://www.volvotrucks.us/trucks/calendar/

probably a new block is needed. 

links to this page: 
 - redirect from /2023wallpapers/
 - there are no links to this page from the content.

**Comment by rrusher** [comment]
I created the page using Teaser Cards block. The high res images need to be adjusted.
