### ISSUE TITLE
Turbo D13 Calculator Not Working on Canadian Sites 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#368]
The D13 Calculator is not working on the English or French-Canadian websites. There may be an issue with the form as all options are not automatically pre-filling and you can't see options listed in the drop downs. The results are undefined as seen in screenshots. 
It's working as expected on the US website. 

https://www.volvotrucks.ca/en-ca/trucks/powertrain/d13tc/turbo-compounding-calculator/
https://www.volvotrucks.ca/fr-ca/trucks/powertrain/d13tc/turbo-compounding-calculator/

![image](https://user-images.githubusercontent.com/125895595/233479062-38c1c641-b6dc-4973-8c08-60cfcbf2979e.png)
![image](https://user-images.githubusercontent.com/125895595/233479139-44472759-818b-449a-9e62-ea4035f617c2.png)
![image](https://user-images.githubusercontent.com/125895595/233479221-0f69f11e-e492-4193-91cb-4882b16b56a2.png)

**Comment by synox** [comment]
@ZoeBeykirch https://www.volvotrucks.ca/ has not been migrated yet, therefore this is not the right place to report this error.
