### ISSUE TITLE
Youtube videos are not loaded after accepting cookies

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-volvotrucks-us#376]
Accepting cookies does not show youtube videos.

<img width="666" alt="obraz" src="https://user-images.githubusercontent.com/125962117/233636929-4cd97c92-4fd6-40d4-9d5e-7cec4a843291.png">

<img width="798" alt="obraz" src="https://user-images.githubusercontent.com/125962117/233636882-0da1ab66-b33b-482e-b334-deeacf6b9ca0.png">

Expected results:
When Social Media Cookies are accepted youtube videos should be shown.

**Comment by synox** [comment]
Also the videos on https://www.volvotrucks.us/our-difference/uptime-and-connectivity/ are not shown. 
<img width="1415" alt="Screenshot 2023-04-21 at 11 24 09" src="https://user-images.githubusercontent.com/2250964/233708631-cc6bb958-c0fc-4132-a87e-f9d88454ba08.png">
