### ISSUE TITLE
Defect: A Model for Uptime banner points to preview instead of production

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#379]
**URL:**
https://www.volvotrucks.us/our-difference/uptime-and-connectivity/

**Description**
One of the banners on the Uptime and Connectivity page links to an article on Staging instead of production. The link goes to: https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/a-model-for-uptime/

The page would need to be published to production for it to be seen by the public instead of in preview. The Production link is: https://www.volvotrucks.us/news-and-stories/volvo-trucks-magazine/a-model-for-uptime/

**Screenshot**
<img width="835" alt="Links to item on staging" src="https://user-images.githubusercontent.com/126615590/233652543-0e249f49-e741-409c-87ca-859e366bc23f.PNG">

<img width="876" alt="Preview link" src="https://user-images.githubusercontent.com/126615590/233652886-20f16c0e-0db0-4652-b4c8-349686c696b3.PNG">

**Comment by rrusher** [comment]
This was a typo in the hyperlink in the document.
"https://main--vg-volvotrucks-us--hlxsites.hlx.page/https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories..."

I corrected a couple locations that I found with this issue.
