### ISSUE TITLE
Defect: Major: Clicking subscribe button does not take user to desired page

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#392]
Steps:
1. navigate to https://www.volvotrucks.us/news-and-stories/volvo-trucks-magazine/cover-story/
2. Click on subscribe

Actual:
Nothing happens as click is not navigating to expected subscribe page

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/234275819-cdb55049-97a9-486d-9bc5-c76e587850a1.png">

**Comment by rrusher** [comment]
Line 114 of /templates/magazine/magazine.js needs to be changed to `#form59`.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, agree with the defect closure.
