### ISSUE TITLE
Redirects for asset URLs with special charecters

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-volvotrucks-us#404]
Need to have a solution to redirect URLs with special characters link:

Example:
https://volvotrucks.us/~/media/VRD/Prevost/15_P042200.pdf

Should be redirected to:
https://volvotrucks.us/media/VRD/Prevost/15-p042200.pdf

**Comment by synox** [comment]
The Franklin team is working on this, I will report back then I have an update.

**Comment by synox** [comment]
This is now fixed and I updated the redirects.xlsx. 

Internally, 
 - `/~/media/VRD/Prevost/15_P042200.pdf` is first redirected to 
 - `/-/media/VRD/Prevost/15_P042200.pdf` and then we have a redirect from this to 
 - `/media/VRD/Prevost/15-p042200.pdf`.
