### ISSUE TITLE
Videos To be played based on cookie consent value

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-volvotrucks-us#41]
Video player needs to play videos based on OptanonConsent cookie value.
If Cookie value is 0 Videos to be played from local DAM.
If value is 1 Videos to be played from YouTube.

**Comment by Buuhuu** [comment]
Relates to #27

**Comment by Kannan-CM** [comment]
There is also an embedded component which needs to have the similar behavior. Please visit the below link for reference:
https://www.volvotrucks.us/trucks/vnl/interior/

**Comment by Buuhuu** [comment]
Created a another issue for the video embed #63
