### ISSUE TITLE
Bug Minor: Hover over text/label is not displayed on forms (Contact us, Contact a Dealer)

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#419]
Step:
1. Navigate to https://www.volvotrucks.us/about-volvo/contact-us/contact-us-form/
2. Validate the hover over text
Then,
3. Navigate to https://www.volvotrucks.us/trucks/powertrain/d13tc/turbo-compounding-calculator/
4. Validate the hover over text on 'contact a dealer' form

Expected vs Actual:
Hover over text is not displayed:
**Contact us:**
![image](https://user-images.githubusercontent.com/125972657/235905873-dfd16680-2d52-4478-9ae8-6e6bc9e6dc2d.png)

**Contact a Dealer:**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/235906157-80242884-f6b4-40a6-bc13-4262c5b30c2e.png">

**Comment by BeckyMedlin** [comment]
@Gonzalo-CG Please close as this will be resolved with the switch to Account Engagement. Thanks!
