### ISSUE TITLE
Need Atom feed for News articles

### ISSUE THREAD

**Issue by Kannan-CM** [hlxsites/vg-volvotrucks-us#421]
Need to create an RSS feed for https://www.volvotrucks.us/news-and-stories/press-releases/ to be consumed by 3rd party applications

**Comment by synox** [comment]
@Kannan-CM the new feed url is https://pr-rss--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/feed.xml

feel free to link it in the website.
