### ISSUE TITLE
Defect: Minor - Search results - Empty category with no text displayed under Category

### ISSUE THREAD

**Issue by Andrei-Boiangiu** [hlxsites/vg-volvotrucks-us#424]
When performing a Search - on the Search results page there is no text on one of the checkboxes under Category

![image](https://user-images.githubusercontent.com/127409602/236137450-1caab132-11c8-484f-994b-c2fa5fe5def4.png)

**Steps to reproduce:**
1. Go to volvotrucks.us and perform a Search
2. Notice the empty text checkbox under Category

**Expected result**
Checkbox should not have empty text. should say "All" (?)

**Actual result**
An empty text checkbox is displayed under Category on Search results page

![image](https://user-images.githubusercontent.com/127409602/236137752-43e1f44d-1655-4b52-9ae6-4a44026961d6.png)

**Comment by AngelaFabregues** [comment]
@netmanito has fixed it!

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
