### ISSUE TITLE
Volvo CR: Blue Contract (Hero - Padding - Bullet Points for Icons)

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-volvotrucks-us#438]
Overview of tasks located here in Figma: https://www.figma.com/file/lmxPtgI1kZYujkGmoJQeXO/Service-Contracts?type=design&node-id=606-5942&t=DRyYdInRlKjwH9sP-0

1. Hero should be adjusted according to new PDP design 1440x900 (we will end up with two hero versions old size and new) Then we can apply to other pages as needed like the iTorque page.
2. Padding laid out on the figma for the various sections (slight tweak both desktop and mobile).
3. Padding for Icon Bullet points

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
 
 with a note that the styling of the footer on Tablet and Mobile is the same
 
<img width="378" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/127409602/73f25921-baef-47af-8cc9-57a50f0e7230">

but that is not in the scope of this ticket, it can be addressed separately
