### ISSUE TITLE
Post Go Live Bug: Major: homepage grid is bleeding into the card components underneath

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#444]
On the volvotrucks.us home page, the first grid component is bleeding into the card component underneath, seen in the screen shot below. 

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/ce66b9f1-fef5-4bf5-b3e7-051c526b998d)

**Comment by girishdigrajkar** [comment]
Confirmed as Fixed
