### ISSUE TITLE
Enhancement: Increase the size of 3 stats displayed on I-Torque page

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#446]
The Volvo team would like to enhance the section seen in the image below on the following page to increase size of 3 stats on desktop to match the Figma file below: https://www.volvotrucks.us/trucks/powertrain/i-torque/

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/349d54ee-c58e-445a-aba0-4ffd8d6333f3)

Figma design to reference, and send Zoe Beykirch a slack message if any access is needed: 

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/90fc7ae8-849c-46b6-84d3-7bc220046495)

**Comment by shirin27** [comment]
**Design link**: https://www.figma.com/file/Qg60TL7LpVlvdmtpNjLjxz/I-Torque?node-id=1554%3A8873&mode=dev

**Acceptance criteria**
- The content on the page https://www.volvotrucks.us/trucks/powertrain/i-torque/ matches the new design provided
- Changes:


![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/b483db9d-7ed4-4298-bcc7-ac40dea70874)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/4ade074d-63fb-4de8-88d5-6e6590988912)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/f768009f-5cb4-4142-b3ca-0b6111a40d62)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/98c471be-134b-4548-887c-589db4864ca1)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/b05070f9-0bee-454f-98a6-37b5bed32789)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/df44455f-8d6b-4270-8566-dd9b32af35ed)
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/135319298/5b1fb8af-062b-4ac8-b6b6-433d5ecfd9e5)

**Comment by shirin27** [comment]
Ticket created in the re-design repo: https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/31

@ZoeBeykirch fyi
