### ISSUE TITLE
Post go-live: Update GTM code of volvotrucks.us 

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-volvotrucks-us#447]

**Comment by girishdigrajkar** [comment]
**Confirmed as Fixed**   

**Expectations** : Accept all the Cookies ( Or, at least performance) >> GTM should show;  GTM should not show in case  performance cookies are declined. If only social media cookies are expected then GTM should not show.


**Steps to test :**
 1. Accept all the Cookies  >> GTM should show in Network requests

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/94032970-caad-4976-8864-7e8473aaf554">
Able to see GTM request:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/13c4d4eb-823f-4664-9c8f-400e3873e1dd">


2: Reject all the cookies >> GTM should not be displayed in Network requests
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/0fcc5c0c-ffc8-49ce-b7ed-54047d3db7f1">
No GTM request as expected
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/4673b9c9-2c32-48c0-b5d0-0c04e14a1dbc">

3. Accept  at least one i.e. performance  cookies:  GTM should show in Network requests
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/ccf0f8f0-a68b-41ba-b354-98a090c3a1fb">

Able to see GTM request:
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/91fed7ba-93d1-4d1e-b94e-d44f10965b31">

4.   Accept only Social cookies:  GTM should not be displayed in Network requests
<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/3eb61aa6-8925-46a0-94bc-1a90ca633eb1">

<img width="960" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com/assets/125972657/96f8cad8-53e1-4dc6-87f9-3e0a6e709122">
