### ISSUE TITLE
 Add New Icon on Volvo Blue Service Contract Page

### ISSUE THREAD

**Issue by TomaszDziezykNetcentric** [hlxsites/vg-volvotrucks-us#451]
Issue copied from Volvo truck CA  - it should be implemented in the US scope (confirmed with Zoe)
https://github.com/hlxsites/vg-volvotrucks-ca/issues/44
---

We have a new icon attached that should replace the truck icon for Adaptive Maintenance in both sections

![obraz](https://github.com/hlxsites/vg-volvotrucks-us/assets/125962117/0ed60f75-0dd0-4036-bb37-464170e088d4)
![obraz](https://github.com/hlxsites/vg-volvotrucks-us/assets/125962117/b5c53ffe-e12c-4f51-be61-dd661cef6cd7)

https://www.volvotrucks.us/purchasing-a-truck/service-contracts

**Comment by Andrei-Boiangiu** [comment]
confirmed as fixed
