### ISSUE TITLE
NFR: Volvo hotjar code

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#456]
Volvo Code (version 2)

<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:1139895,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
;
;
;

**Comment by girishdigrajkar** [comment]
Validated and able to see "_hjXXXX" cookies getting triggered

@Kannan-CM, @Varunvolvo  : These cookies are getting triggered bydefault as soon as volvotrucks.us is accessed
Please confirm the cookie classification as in case if needed only in case targeting cookies are accepted then, code change would be required. 

fyi: @manuel-vara , @jonatan-lledo-netcentric , @shirin27 

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/10ad0be4-be9c-4c0c-a731-fe9c7566af29">

**Comment by Kannan-CM** [comment]
@girishdigrajkar , fbp is a facebook pixcel script which should be blocked by default.

**Comment by girishdigrajkar** [comment]
Thanks @Kannan-CM
 Could you please also confirm on hotjar cookie... thanks

**Comment by Kannan-CM** [comment]
HotJar needs to be loaded by default.

**Comment by manuel-vara** [comment]
> HotJar needs to be loaded by default.

No need for OneTrust Targeting Cookie consent then?

**Comment by Kannan-CM** [comment]
Sorry,
Hotjar needs to be added under performance cookies and loaded once user accepts it.

**Comment by girishdigrajkar** [comment]
Based on above confirmation, it needs to be reworked / integrated with performance cookies logic.

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd Looks like this work is incomplete. Please confirm with team and let's get it planned for a future sprint.

**Comment by manuel-vara** [comment]
I confirm, the integration within performance cookies group still needs to be done

**Comment by DanielaPedrochevd** [comment]
Blocked until integration  within performance cookies is done @manuel-vara is there any issue open for this?

**Comment by jonatan-lledo-netcentric** [comment]
hotjar script is already loaded under performance allowance
