### ISSUE TITLE
Bug: Major: Volvotrucks :  "fbevents.js" triggers although  the user has turned off Social media cookies

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#457]
Steps:
1. Navigate to https://www.volvotrucks.us/
2. Turn off "Social Media Cookies"
3. Validate the Network tab in developer options

Expected vs Actual:
"fbevents.js" triggers although  the user has turned off Social media cookies
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/41d4c2b5-d6e3-4741-bdf1-08f3b52ae139)

**Comment by girishdigrajkar** [comment]
Validated and failed for the case when user selects 'social media cookies' and later on disables them.  hence, reopening the defect.

**When accepted Social Media cookies:**
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/d6bd4cf3-8b97-4377-b745-1da22f98aef9)

**When accepted social media cookies initially and rejected later :**
fbevents.js should not be triggered post the social media cookie is rejected.
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/21b11bd7-8f12-455a-b8e2-88e4195174a5)

**Bydefault, when site is opened :**
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/29fa2dc4-f215-4fed-9693-2ccdd351ca8d)

**Comment by girishdigrajkar** [comment]
Validated and able to see the fbevents.js in case user turns on only performance cookies too thus, reopening the bug.

**Comment by jonatan-lledo-netcentric** [comment]
@Kannan-CM @Varunvolvo fbevents script is loaded twice, one when performance cookies are accepted because GTM loads it, and the other is when the social media cookies are accepted because the delayed.js from Franklin adds it, so I recommend removing the Pixel script from GTM and let be load only when social media cookies are accepted IMHO, WDYT?

**Comment by Gonzalo-CG** [comment]
If performance & social media are accepted --> pixel script should only be injected by GTM.
If performance is not allowed & social media is allowed--> pixel script is injected by delayed.js

**Comment by DanielaPedrochevd** [comment]
linked to #489

**Comment by girishdigrajkar** [comment]
Retest Failed :

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/51203fd3-ca82-40d6-ac4f-a07181e89e33">

**Comment by jonatan-lledo-netcentric** [comment]
if performance is accepted but not Social media -> GTM loads anyway fbevents and I tried to removed it, so. what can we do then

**Comment by manuel-vara** [comment]
IMO, it needs to be removed from GTM console. @Kannan-CM , is that possible?

**Comment by Kannan-CM** [comment]
I have removed the Facebook pixel from Firing through Google Tag Manager.
Please validate and let me know if it looks okay on your end

**Comment by DanielaPedrochevd** [comment]
Spillover because we needed to raise a new PR since we will have to remove the check, this will be reviewed but it means it will be a spillover.

**Comment by girishdigrajkar** [comment]
Validated and able to get the below correct results and hence, this ticket could be marked to done status:

**If Social media cookie is turned ON >> Fbevents.js should be available in Network tab irrespective of status of other cookies**

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/79f043d5-6b68-4db4-b1d3-689d01241cd9">


**If Social media cookie is turned OFF >> Fbevents.js should NOT be available in Network tab irrespective of status of other cookies**

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/cb6061fd-edcd-4f44-babd-8e675ca89bd6">

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/71b36b74-418a-4b21-99d6-782045b04787">
