### ISSUE TITLE
Add brand logos and language swith to the recall page

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-volvotrucks-us#468]
**User story:**
As a visitor of the recall page, I want to be able to see a list of available brands for the recall lookup and have the option to switch to a different language when applicable.

**Acceptance Criteria:**
1. Brand List Display:
    * On the recall page, there should be a prominently displayed list of brands for which recall lookup is available.
    * Logos need to be the same height.
2. Language Selection Option:
    * If the country is multilingual, there should be a language switch option, allowing users to choose their preferred language, this is only applicable for Canada
3. Language Switching Functionality:
    * When a user selects a different language, the content of the recall page, including brand names and any associated information, should be displayed in the selected language.
4. Responsive Design:
    * The brand list and language selection option should be responsive and display correctly on various screen sizes and devices, including desktop, tablet, and mobile.

**Definition of Done:**
* The brand logos are displayed on the page 
* The language change button is available on the page
* The button works and points to the respective language
* Responsive design is taken into account

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
as discussed and confirmed with @Lakshmishri on the updated acceptance criteria
