### ISSUE TITLE
Add links to recall pages within the footer

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-volvotrucks-us#470]
**User Story:** 
As a user of our website, I want to easily access recall pages related to product safety and information directly from the website footer, so that I can quickly find information about product recalls and safety alerts.

**Acceptance Criteria:**
1. Footer Links Addition:
    * In the website footer, there should be links added to access recall pages related to product safety and information.
2. Link Text and Icons:
    * Each link in the footer should have clear text and optionally, appropriate icons to visually represent the links.
3. Clickable Links:
    * The footer links should be clickable, directing users to the respective recall pages when clicked.

**Definition of Done:**
* The links to recall pages have been added to the website footer.
* The links point to the correct recall page per brand

**Comment by BeckyMedlin** [comment]
@ZoeBeykirch Is this needed?
