### ISSUE TITLE
Update the styling of the accordion block to accomadate for the recall information

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-volvotrucks-us#471]
**User Story**
As a user of the recall page I want the accordion component to have an updated styling to make sure the recall information is displayed correctly and easy to read and understand

**Acceptance Criteria:**
1. Accordion Styling Update:
    * The accordion component's styling should be updated to properly fit the recall information
2. Responsive Design
    * The accordion should be responsive and display correctly on various screen sizes and devices, including desktop, tablet, and mobile.
3. Accordion Icons:
    * Update or replace any icons used within the accordion to match the new styling.

**Additional Notes:**
* First implementation is to reuse the current styling as much as possible and change only what is necessary. If needed additional styling can be handled in a separate ticket.

**Comment by mlee001** [comment]
Story points based on if change is needed

**Comment by Andrei-Boiangiu** [comment]
confirmed as done 
as tested on https://471-nhtsa-accordion-styling--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
