### ISSUE TITLE
Introduce a campaign header and footer within Volvo Trucks and Mack Trucks

### ISSUE THREAD

**Issue by mlee001** [hlxsites/vg-volvotrucks-us#483]
**User story**

As a marketing team member, I want a campaign header so that we can effectively promote our upcoming campaign or event without distracting with other navigation items.

**Acceptance criteria**

1. The header shows a logo in the top left.
2. Compared to the existing header the links and icons are removed.
3. There can be links placed on header that the content editor can change the written text content and hyperlinks. 
4. Icons can be used as a hyperlink
5. There is a mechanism to be able to use the campaign header for a new page.
6. There is a button CTA within the header on the top right-hand corner. 
7. Footer is set to a minimum with only brand logo, social and legal links.
8. This is available for Mack and Volvo brand

**Comment by BeckyMedlin** [comment]
@mlee001 This is an enhancement. We need to deploy the existing global header for the initial release. We can add these changes later.

**Comment by ZoeBeykirch** [comment]
Update - the Volvo header/footers and Mack footer are complete, last item pending is the new Mack header, which had a dependency on the release of the new navigation so Lakshmi could repurpose the new code. The new Mack nav has been published, so this blocker is now clear. 

Volvo header - https://483-header-footer--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
Volvo footer - https://483-header-footer--vg-volvotrucks-us--hlxsites.hlx.page/fr/recalls/
Mack footer - https://483-hf-config--vg-macktrucks-com--hlxsites.hlx.page/nhtsa/

**Comment by Lakshmishri** [comment]
Volvo - the custom header and footer is merged.
Mack trucks - the custom footer is developed and header should be developed

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
 as discussed and confirmed with @Lakshmishri on the updated acceptance criteria
