### ISSUE TITLE
CR: Update Footer social media title "Twitter" to "X"

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-volvotrucks-us#487]
### Description
Since Twitter is now called X, the footer's social media title "Twitter" next to the icon must be replaced with the new "X"

### Acceptance Criteria
- [ ] The Twitter title on the footer is replaced by the new X title

Image:
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/139977780/7da1e676-745f-4d9b-8264-275ec9ed3b70)

Notes
[Font Awesome x-twitter Icon](https://fontawesome.com/icons/x-twitter?f=brands&s=solid)

**Comment by BeckyMedlin** [comment]
This CR can wait until all other necessary migration work is completed.

**Comment by ZoeBeykirch** [comment]
Closing as not needed.
