### ISSUE TITLE
High Priority: Dealer Locator - Missing Google Logo and Copyright Text

### ISSUE THREAD

**Issue by Joesturbo** [hlxsites/vg-volvotrucks-us#488]
Showing for representation only - the logo and also text at the bottom. Was this codded out somewhere?

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/122567401/cd224223-f085-47e2-b414-611d40501c00)

**Comment by manuel-vara** [comment]
Santiago FYI, as you are now dealing with this block, can you have a look to this one, please?

**Comment by Gonzalo-CG** [comment]
Will be fixed by #492

**Comment by SantiagoHomps-NC** [comment]
@Joesturbo Do we have an answer on the one-trust issue with the logo? 
Should we move it to the right of the sidebar?
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/103571932/95b8b02a-30ca-40e0-ad61-e49a834c3a8f)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the defect to done status:

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/dc000458-8d84-4a8a-ae0a-8b00f3e6b540)

**Comment by Joesturbo** [comment]
This issue can be closed as we resolved the text in the bottom right. Our partner was satisfied with the result and resolution on each device changes certain aspects.
