### ISSUE TITLE
CR: add hotjar script under performance cookie clearance

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-volvotrucks-us#489]
Hotjar has to be run only if the performance's cookie is allowed. The performance cookie is 'C0002'

**Comment by DanielaPedrochevd** [comment]
linked with #457

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results hence, marking the ticket to done status:

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/47b22a86-802d-4476-8e54-575dcb88e0c2)
