### ISSUE TITLE
NFR: Update NHTSA API URLs from pre-production to production URLs (dependency) 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#496]
Once the Volvo and Mack NHTSA APIs are deployed to production, the current testing pre-production URLs will need to be changed to the updated production URLs. This has a dependency on Volvo internal architecture reviews with one last approval pending that is required in order to start this work. This ticket will serve to update the following 3 NHTSA pages: 

https://main--vg-volvotrucks-us--hlxsites.hlx.page/fr/recalls/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
https://452-nhtsa-setup--vg-macktrucks-com--hlxsites.hlx.page/nhtsa/

**Comment by BeckyMedlin** [comment]
New Endpoints for QA and Prod:

Below are the endpoints for QA and PROD.

QA: [https://vinlookup-qa-euw-ase-01.azurewebsites.net/v1/api/vin/{VIN}?api_key=0e13506b59674706ad9bae72d94fc83c&mode=company](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvinlookup-qa-euw-ase-01.azurewebsites.net%2Fv1%2Fapi%2Fvin%2F%257bVIN%257d%3Fapi_key%3D0e13506b59674706ad9bae72d94fc83c%26mode%3Dcompany&data=05%7C01%7Cbecky.medlin%40volvo.com%7C6bd9f1b2c23a4d9a3c2208dbe551eaff%7Cf25493ae1c9841d78a330be75f5fe603%7C0%7C0%7C638355912220059601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FViMJC5vO9MM04htxuKpcsVDiQRn2Gh3CsF%2FL9hFdME%3D&reserved=0)


PROD: [https://vinlookup-prod-euw-ase-01.azurewebsites.net/v1/api/vin/{VIN}?api_key=0e13506b59674706ad9bae72d94fc83c&mode=company](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvinlookup-prod-euw-ase-01.azurewebsites.net%2Fv1%2Fapi%2Fvin%2F%257bVIN%257d%3Fapi_key%3D0e13506b59674706ad9bae72d94fc83c%26mode%3Dcompany&data=05%7C01%7Cbecky.medlin%40volvo.com%7C6bd9f1b2c23a4d9a3c2208dbe551eaff%7Cf25493ae1c9841d78a330be75f5fe603%7C0%7C0%7C638355912220059601%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l%2B5xG7M1Hl6bsL80ozMbE5C69aMyxKjWQrAQz6%2Fje3w%3D&reserved=0)
