### ISSUE TITLE
CR: VIN Lookup separate "Last Update" + "Available Since" display on different lines

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#498]
This change request is to update the VIN Lookup submissions to separate the "Information last updated date" and the "Recall information available since date" information displayed on two different lines. Currently we have the Last Update + Available Since on the same line next to RECALLS, and we realize that this data will ultimately need to be split as shown below. The Last Update date will come in a new piece of information fed by the API. We are suggesting keeping the "Recall Information Available Since" on the same place as it is now, and only moving the "Information last updated: date" to be above the VIN lookup search bar. We are open to developer recommendations for what is the easiest way to accomplish this change request. This will need to be changed on both the Mack and Volvo NHTSA pages. 

**Current:**

![VIN CR](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/669994d8-8996-4ce5-8ee8-60cac0b4a51d)

**Desired:** 

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/6300728a-155a-403e-98af-d6c841a40f6f)

**Comment by ZoeBeykirch** [comment]
@Andrei-Boiangiu  Can you share the link that you tested this with? I'm not seeing these changes reflected on the main link - https://main--vg-volvotrucks-us--hlxsites.hlx.page/recalls/

**Comment by Andrei-Boiangiu** [comment]
@ZoeBeykirch  
 I have tested this on the links provided to me by @Lakshmishri to check these fixes on
 
 https://496-prodqa-url--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
 https://483-hf-config--vg-macktrucks-com--hlxsites.hlx.page/recalls/
