### ISSUE TITLE
Turbo Compound Calculator

### ISSUE THREAD

**Issue by Buuhuu** [hlxsites/vg-volvotrucks-us#50]
We have to rebuild the calculator Widget. 

https://www.volvotrucks.us/trucks/powertrain/d13tc/turbo-compounding-calculator/

The logic is available in a spreadsheet. 

We have a new layout to implement.

**Comment by synox** [comment]
Please provide the spread sheet. 
What do you mean by new layout to implement?

**Comment by Buuhuu** [comment]
Iirc @dkuntze you have the wireframes? The spreadsheet was posted in slack.

**Comment by dkuntze** [comment]
also issue #310
