### ISSUE TITLE
NFR: Acceptance of Volvo Bus Vehicle VINs 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#502]
Non-Functional Requirement: 
As a Volvo Group customer, when I search for my Volvo Bus VIN in the NHTSA lookup too, I should see a valid recall submission for my vin. 

Acceptance Criteria: 
•	The VIN lookup should accept Volvo Bus vehicle on both of the Volvo USA and French CA sites. 
•	WMI: 3CE > Needs to be added as valid VIN

In the screen shot below, it shows how the current VIN lookup tool does not recognize Volvo Bus vehicles as valid VINs, when the example in the screen shot should yield a valid recall result. 
 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/a7e16215-b16c-4112-97e7-c944275e667c)

**Comment by Andrei-Boiangiu** [comment]
the VIN number in the screenshot ( 3CET2W428N5203539 )
 is accepted as valid, as tested on https://496-prodqa-url--vg-volvotrucks-us--hlxsites.hlx.page/recalls/
 but there are no recalls for it
 
 
<img width="1577" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/127409602/aca82e28-8e14-4ebf-a2ba-1c1617418a28">

let me know if this should be tested with recalls returned for that VIN or if there are other VIN numbers to test this acceptance with
cc @Lakshmishri @ZoeBeykirch
