### ISSUE TITLE
FR: Add "Volvo Bus" to VIN Error Message 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#503]
Functional Requirement: 
On both the Volvo USA and French CA sites, please edit the text to include "Volvo Bus" on the VIN error message in the screen shot below that is shown if a user submits a VIN that is not valid. Please replace the VIN error message with the Proposed text below that also re-orders the Volvo Group brands to keep consistence with how they are displayed on the rest of the site. 

Current: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/b0569130-5b3b-4991-95d6-57cb6bd00dbb)

Proposed:
The VIN entered is not valid for Volvo Trucks, Prevost, Nova Bus, or Volvo Bus vehicles

**Comment by Andrei-Boiangiu** [comment]
confirmed as done
