### ISSUE TITLE
Bug: French Volvo recalls page does load any content - only a blank screen

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#510]
When the [French Volvo Recalls page](https://www.volvotrucks.us/fr/recalls/) was published, the page will not load any content and only shows a blank screen, which is not [occurring in the pre-production environment.](https://main--vg-volvotrucks-us--hlxsites.hlx.page/fr/recalls/)

Critical Bug:
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/5d67fff8-3b1b-447c-a84e-dba2d20b9add)

Expected: 
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/00c9e3f5-9fb2-4425-bb0f-2fb18433d62e)

**Comment by BeckyMedlin** [comment]
@Lakshmishri Can this item be closed?
