### ISSUE TITLE
Bug: Brand fonts take 2-3 seconds to load properly 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#520]
Bug steps: When the user arrives at https://www.volvotrucks.us/ or any page on the website, especially when loading it in a private window or arriving at the page for the very first time, the user will see a different font displayed on the website for a few seconds before the correct font files load on the page. The expected behavior for the user is to only see the branded font files without any loading buffer.

1/25 update:
It seems the CSS issue is getting progressively worse after we published the redesigns last week. The wonky font seems to hold on screen longer now, seen in the screen recording (which fails to attach to this ticket - we can send it via slack to the assigned developer if there are any questions in reproducing this issue)

Current bug: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/c789af59-a255-4a9d-ad59-b67e9ad40357)

Expectation: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/77d91def-775e-42a9-9c5c-24eda6ca78da)

**Comment by BeckyMedlin** [comment]
@shirin27 @mollyaljenkins This is also impacting Mack Trucks per Wendy Kruger. Please create a related ticket for the Mack stream. Thanks!

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @SantiagoHomps-NC Has this been fixed during the current sprint? If so, please move it into the sprint.
