### ISSUE TITLE
Dealer locator issues - Volvo US

### ISSUE THREAD

**Issue by SantiagoHomps-NC** [hlxsites/vg-volvotrucks-us#521]
Required functionalities:
-All pins are displayed on the map
-Buttons filter for dealer type
-Open hours are calculated from MAX/MIN of all **Parts/Sales/Service** combined
-Open hours of the day displayed on the sidebar
-Open/Closed display only when dealer is selected
-Timezone is only calculated when dealer is selected

**Comment by girishdigrajkar** [comment]
Validated and **passed**;  Please see attached test summary for more information.

Hi @BeckyMedlin : 

One case for "Only Parts & Service dealer ", we suspect the incoming source data for incorrect value.

Dealer details:
PREVOST - JACKSONVILLE
6931 BUSINESS PARK BLVD N  JACKSONVILLE, FL 32256-2736

Shows 6:30 am- 4:30 pm  on Thursday. Which is Correct per logic however, **open hours for Parts seems wrong.**;  This need to be fixed at source system(Incoming JSON)

 Json  **:  parts  tag has “4” I.e. Thursday start as “8:00 am” &  End as “5:00 am”** 
             Sales tag has “4” I.e. Thursday start as “” &  End as “” 
             Service tag has “4” I.e   Thursday start as “6:30 am” &  End as “4:30 pm” 
           On Call tag has  “4”  I.e. Thursday start as “Closed” &  End as “Closed” 

cc: @SantiagoHomps-NC 
[521 test summary.docx](https://github.com/hlxsites/vg-volvotrucks-us/files/14160992/521.test.summary.docx)

**Comment by BeckyMedlin** [comment]
@girishdigrajkar @SantiagoHomps-NC PREVOST is out of scope for VTNA and Mack dealer locator. Please exclude it.
