### ISSUE TITLE
block: press releases

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/vg-volvotrucks-us#53]
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/
https://www.volvotrucks.us/news-and-stories/

https://main--vg-volvotrucks-us--hlxsites.hlx.page//news-and-stories/press-releases/
https://www.volvotrucks.us/news-and-stories/press-releases/

**Comment by dkuntze** [comment]
pull list from the query index

**Comment by Buuhuu** [comment]
@bpauli please use https://github.com/Buuhuu/ffetch/tree/draft (copy it into `scripts/lib-ffetch.js`)
