### ISSUE TITLE
Add missing test cases for functions in common js

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#538]
From vg-volvotrucks-us-rd created by [Lakshmishri](https://github.com/Lakshmishri): Netcentric/vg-volvotrucks-us-rd#64  

Add code test cases for functions from common JS file. This is to be checked by dev team. 

-  removeEmptyTags
- variantsClassesToBEM

**Comment by ZoeBeykirch** [comment]
Confirmed this can be closed.
