### ISSUE TITLE
Create text block variant to handle Headings tags to be SEO complaint

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#543]
From vg-volvotrucks-us-rd created by [Lakshmishri](https://github.com/Lakshmishri): Netcentric/vg-volvotrucks-us-rd#61  

Create variant to existing text block that handles the heading tags semantically.

- If have text block has various heading tags, order them correctly, but position them using css properties

Example [here](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=1133-19710&mode=dev)

- Transform the subtitle in CSS to a paragraph
- Re-order them in CSS to follow the correct structure (H2, then H3, for example)

**Comment by ZoeBeykirch** [comment]
@bfvolvo to help review this

**Comment by ZoeBeykirch** [comment]
After running SEO report, website scored 100/100 on SEO per Chrome Lighthouse. Therefore, can close this ticket as not needed.

**Comment by bfvolvo** [comment]
SEO report output
[Lighthouse Report SEO.pdf](https://github.com/user-attachments/files/17368498/Lighthouse.Report.SEO.pdf)
