### ISSUE TITLE
Calculator / input slider

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#544]
From vg-volvotrucks-us-rd created by [cogniSyb](https://github.com/cogniSyb): Netcentric/vg-volvotrucks-us-rd#86  

Interactive [input slider](https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=7317-57461&mode=dev) on PDP page

### Requirements
- Link "view savings calculator" will open a modal with current form
- Text in the tooltip changes according to the node that is selected in the slider
- Changing position of the slider changes the numerical values displayed
  - The values will be provided separately in a table
- Colours change [according to context](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=1460-37394&mode=design&t=UXeuvf1juqR4QUJ7-4)

The calculator in the modal is out of scope. In a later stage, use the existing calculator data/functionality. See #97

**Comment by shirin27** [comment]
@ZoeBeykirch please check with the team and come back with the data modeling (what columns will the Excel file have) so we can create the block with "placeholder" numbers.

**Comment by shirin27** [comment]
@DanielaPedrochevd After talking with the team more this ticket can be de-prioritized and put on hold for now. It will take more time for Volvo team to validate the data, and since this new truck model will measure engine savings in a different way than the past calculators have, we don't have a good format for dummy-data to start development. This block is not critical to going live with the PDP page, and it very well may end up being an enhancement post-launch depending on when we receive the data formats after it has been validated.

**Comment by ZoeBeykirch** [comment]
Closing for now, will re-open a new ticket if/when the product managers have data ready
