### ISSUE TITLE
CR: Stories Carousel design changes

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#545]
From vg-volvotrucks-us-rd created by [cogniSyb](https://github.com/cogniSyb): Netcentric/vg-volvotrucks-us-rd#78  

Discussed with client: remove the author from "Stories from the road" carousel due to having no proper content available.

A new, [more consistent design has been created](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=424-8853&mode=design&t=6tco0LYQlMAQBctt-4) for the navigation of the carousel. This is shared with #70 

### Requirements

- The title should be changed, everything behind the pipe character should be stripped 
- Buttons with previous/next arrows are used to navigate
  - When the start or the end of the carousel is reached, the respective button will be shown as inactive
  - Buttons are only present on tablet and desktop
  - On tablet, the navigation buttons are placed on the sides of the text
  - On desktop, the navigation buttons are placed near each other
- Text will be truncated if too long
  - If the title text exceeds 1 line, text will truncate
  - If the body copy text exceeds 2 lines, text will truncate
- Retrieve a maximum of articles, [as mentioned](https://github.com/hlxsites/vg-volvotrucks-us/issues/600#issuecomment-2051740862) in #600
- This block can be displayed on article pages and home pages 

Desktop: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/158284953/b5b39cc2-ac67-425a-8a43-a001be6ef694)
Tablet: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/158284953/d308a880-508b-463c-825a-6c8e1a8a2626)
Mobile: 
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/158284953/1ba2a835-4de0-4b86-9312-5b7b3a9b6e7c)

**Comment by shirin27** [comment]
@cogniSyb What do you mean this issue is shared with #70? Can we refine this today?

**Comment by shirin27** [comment]
@DanielaPedrochevd I mean here that we have a new design for the arrow navigation of this block.

We would need to add #171 to this issue as well.

**Comment by shirin27** [comment]
related to #70

**Comment by shirin27** [comment]
@ZoeBeykirch @DanielaPedrochevd I think we should adjust the requirement from #171 "The title can be modified by the content editor". On the block itself this is not possible.

I understand the wish of the business here. Looking at how the magazine is built, I propose the following:
1. Just like magazine article pages we remove all content of the title after a vertical bar then "Business Story Walking the Walk | Volvo Trucks USA" will become "Business Story Walking the Walk"
2. We add a new item to the page metadata for magazine articles, an alternative title. This can be then reused properly in other parts of the website. All current magazine articles will need to contain this extra metadata field

For forward compatibility, I propose solution 2. It will mean less complexity later on when we touch the code of the magazine.

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @verareljic #560 notes that this ticket must be completed before #541

**Comment by AsmitKMishra** [comment]
There are couple of points to be clarified:

**Comment by AsmitKMishra** [comment]
There are couple of points to be clarified:
1. which is the Figma design to be referenced. Is it this one [link1](https://www.figma.com/file/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?type=design&node-id=424-8853&mode=design&t=6tco0LYQlMAQBctt-4) or is it this one [link2](https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1574%3A20616&mode=dev). 
The main difference in both being one has author name and the other does not.
2. Other point is related to buttons. When carousel reaches start or end the button is disabled. Does it need a visual cue as well? (eg: Change in color).

**Comment by amglebihan** [comment]
@AsmitKMishra 

1. It's the first [link](https://www.figma.com/design/Id3nd9kbfh8TpS1SfWhrW2/Volvo-Component-Library?node-id=424-8853&t=zdDGkGH1diKWkj88-0).
2. I've changed the opacity of the buttons when inactive.
