### ISSUE TITLE
block: subscribe

### ISSUE THREAD

**Issue by dkuntze** [hlxsites/vg-volvotrucks-us#55]
![image](https://user-images.githubusercontent.com/171559/222264247-1836b8ae-1ea2-4e0c-8d62-644e4b3c93f9.png)

https://www.volvotrucks.us/news-and-stories/volvo-trucks-magazine/
https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/volvo-trucks-magazine/

looks like another eloqua form.

**Comment by Buuhuu** [comment]
Should be in scope of #30 30
