### ISSUE TITLE
FR: Volvo Trucks Compound Calculator Modal 

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#550]
From vg-volvotrucks-us-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-volvotrucks-us-rd#179  

**Agile Requirement**
As a user, I want to be able to calculate how much money I would be saving on gas depending on the characteristics of the truck I select and its motor so that I can buy the truck that best suits my needs. 

https://www.figma.com/file/yv0VtHTvMoGPqkv0RAYcVp/PDP?type=design&node-id=8465-51236&mode=design&t=ZPrXUdQRUIIO3ABZ-4

**Comment by shirin27** [comment]
Per discussion with @williebender, this item can be placed on hold for now. Awaiting information.

**Comment by BeckyMedlin** [comment]
Closing as data is still unavailable. A new ticket will be created once data is available. @williebender
