### ISSUE TITLE
FR: Volvo Trucks Magazine Sub navigation

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#551]
From vg-volvotrucks-us-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-volvotrucks-us-rd#184  

**Agile requirement**
As a business owner I want my page to have a top bar as in the design https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=439-13305&mode=design&t=kL4IVGVfxBx0On3x-0. 

**Description** 
Update the header block to show the new bar if we are under the magazine area. The elements of this bar are: 

- Subtitle
- Call to action

**Acceptance criteria**
- The editors can define in the header block the text for the subtitle and the link and text of the CTA
- This will only be loaded in the area the editors decide to be loaded

**Future enhancement**
- Check if the user has subscribed already and do not show the CTA to that user

**Comment by shirin27** [comment]
Kamino cloned this issue to [hlxsites/vg-volvotrucks-us](https://github.com/hlxsites/vg-volvotrucks-us/issues/531)

**Comment by ZoeBeykirch** [comment]
Closing ticket as new magazine designs will not use a sub-navigation.
