### ISSUE TITLE
FR: Volvo Trucks Magazine Secondary Featured

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#554]
From vg-volvotrucks-us-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-volvotrucks-us-rd#187  

**Agile Requirement**
As a business owner, I want to display a list of articles in a carousel way so that users can navigate through the different articles. 

https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=439-13321&mode=design&t=yOTLUJc3IbmBU8Oy-4

**Comment by shirin27** [comment]
Is it possible to check if it's similar to stories from the road and reuse it?

**Comment by shirin27** [comment]
@DanielaPedrochevd Component on the homepage is very similar. Definitely need to reuse components when and where possible.

**Comment by ZoeBeykirch** [comment]
Closing this ticket as the new magazine design updates do not display the list of articles in a carousel block.
