### ISSUE TITLE
NFR: Google Analytic 4 Custom Tag Implementation

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#557]
From vg-volvotrucks-us-rd created by [ZoeBeykirch](https://github.com/ZoeBeykirch): Netcentric/vg-volvotrucks-us-rd#201  

Placeholder ticket - investigate how to implement custom GA4 tags to enhance our analytic tracking across all websites. We will start with Volvo Trucks USA, and would like to apply this framework to all of our AEM websites (Mack, RoadChoice, etc). 

More documentation for exact custom GA4 tags coming soon! 

Assigned to @manuel-vara to begin investigations as a follow up from our conversation today.

**Comment by BeckyMedlin** [comment]
Per discussion with @Joesturbo and @Kannan-CM , this work has been completed as part of the launch.
