### ISSUE TITLE
Template: Magazine Article - Next Article

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#563]
From vg-volvotrucks-us-rd created by [Gonzalo-CG](https://github.com/Gonzalo-CG): Netcentric/vg-volvotrucks-us-rd#214  

### Business Value
As a content author, I want to implement a 'Next Article' feature at the bottom of each article to enhance user retention and encourage continued engagement, thereby increasing page views and overall site usability.

### Description
A block that shows the title of the next article and links to it will be developed to be used in the [#211 - Template: Magazine Article](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/211).

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/139977780/ece91b3c-96ef-40b8-9316-caa34b22b7ad)

### Acceptance Criteria
- [ ] The block follows the design shown on [Magazine Article - Figma](https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=446-14331&mode=design&t=0u0tpYWDGszH8T6j-0).
- [ ] The block can be added to the [#211 - Template: Magazine Article](https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/211).

**Comment by ZoeBeykirch** [comment]
Closing this ticket as the new updated Magazine designs do not use a "next article" component.
