### ISSUE TITLE
CR - Truck Carousel description font weight is heavier than what is displayed in Figma

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#565]
From vg-volvotrucks-us-rd created by [ZoeBeykirch](https://github.com/ZoeBeykirch): Netcentric/vg-volvotrucks-us-rd#220  

For the Truck Carousel block on the [new homepage](https://www.volvotrucks.us/), the truck description font weight and size are different than what is displayed in Figma. 

Current Result:

![Image](https://github.com/user-attachments/assets/ed90401c-506c-44f3-a143-f4e501a6212d)

Desired Result:
https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4259%3A4276&mode=dev

![Image](https://github.com/user-attachments/assets/b5e4e70f-81c4-4d16-89e5-c36dad70c7e5)

**Comment by shirin27** [comment]
This part of the design has been changed along the way. The `font-weight` is 350, which is different from the rest of the regular text (400). I ran through the rest of the designs, and we also have the pretitle with font-weight 300. Can I safely assume that we would need to add "Volvo Novum SemiLight" and "Volvo Novum Light" to the project?

Performance-wise I don’t want to add two new font files to the project, especially if their appearance is so similar. Can we pick one weight to use for both pretitle and this text?

**Comment by shirin27** [comment]
@csulitzer Based on discussion with Saamia/Ozzy this morning, please update this ticket once design team has a recommendation

**Comment by BeckyMedlin** [comment]
Burundi needs to weigh in on this item.

**Comment by bfvolvo** [comment]
Hello @shirin27 I am catching up to this issue, can you explain where you are seeing the "pretitle" I am looking at https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2 and the example you mention. In inspecting the code for that section, I get the following. 

![image](https://github.com/user-attachments/assets/19f6120a-93cb-458c-b9dd-b192f63ebc08)

Also, if we are to match the Figma file it would appear currently the design has the text as Volvo Novum at 300 the only difference is the color which I illustrate below:

![image](https://github.com/user-attachments/assets/b4fa7e28-8895-4252-99af-37a7085f1aa4)

**Comment by bfvolvo** [comment]
Hello @williebender do you think we need to change the font in the area suggested above? 
As stated, above I think visually its appealing.

If we do stay with the current font usage it may be best to also update the Figma designs to keep consistency.

![image](https://github.com/user-attachments/assets/e5a53160-6568-4a64-bd13-8d215c2efb8f)

**Comment by williebender** [comment]
@bfvolvo thanks for flagging. I agree, I think the current styling is easier on the eyes – let's leave as is. We can close this one out

**Comment by BeckyMedlin** [comment]
Closing per @williebender. Thank you @bfvolvo and @williebender
