### ISSUE TITLE
FR - Android - Correct Error prompt on Subscribe to newsletter field overlaps the Submit button

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#566]
From vg-volvotrucks-us-rd created by [Andrei-Boiangiu](https://github.com/Andrei-Boiangiu): Netcentric/vg-volvotrucks-us-rd#266  

On an Android phone, when adding an invalid input in the Subscribe to newsletter field and clicking submit - the error prompt overlaps the Submit button

**Steps to reproduce:**
01. Go to https://245-subs-form-response--vg-volvotrucks-us-rd--netcentric.hlx.page/drafts/manuel.vara/homepage-test and scroll down to the Submit to newsletter section
02. Input invalid email or leave field empty and click Submit
03. Notice that the error prompt overlaps the Submit button

**Expected result**
Submit button should still be visible

**Actual result**
The error prompt overlaps the Submit button

![image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/127409602/ab234588-3d6a-423f-8bae-ca59bacd2090)

**Comment by shirin27** [comment]
#245

**Comment by shirin27** [comment]
This issue is not a bug but an enhancement. Sadly we can’t do anything about the browser functionality except for disabling the validation. This issue is present on other sites as well. So I’d rather note this as a known

**Comment by ZoeBeykirch** [comment]
Closing as this is not present on production.
