### ISSUE TITLE
CR - Desktop - remove white gradient from Stories on the road block

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#568]
From vg-volvotrucks-us-rd created by [ZoeBeykirch](https://github.com/ZoeBeykirch): Netcentric/vg-volvotrucks-us-rd#225  

For the Stories from the road block on the [redesign homepage](https://main--vg-volvotrucks-us--hlxsites.hlx.page/homepage-v2), on desktop view the white gradient on right edge of carousel should be removed. Mobile seems to be rendering correctly. 

Current Result: 

![Image](https://github.com/Netcentric/vg-volvotrucks-us-rd/assets/125895595/d8f99b95-7e7f-4a16-a879-0e7cfa8ec24e)

Desired Result: 
https://www.figma.com/file/IcqreRKnNYyDVMc28yoOeh/Homepage?type=design&node-id=4282%3A5564&mode=dev

**Comment by shirin27** [comment]
The gradient enhancement was presented to the client by our developer https://github.com/Netcentric/vg-volvotrucks-us-rd/issues/28 I'll close this ticket and ask the design team to update it in figma

**Comment by ZoeBeykirch** [comment]
Closing ticket as now fixed after https://github.com/hlxsites/vg-volvotrucks-us/issues/545 is released.
