### ISSUE TITLE
CR - Modal Sliding motion

### ISSUE THREAD

**Issue by shirin27** [hlxsites/vg-volvotrucks-us#569]
From vg-volvotrucks-us-rd created by [DanielaPedrochevd](https://github.com/DanielaPedrochevd): Netcentric/vg-volvotrucks-us-rd#298  

**Agile requirement**

As a business owner, I would like the modal to open sliding from the bottom of the screen and close moving down to achieve a nicer user experience. 

**Description** 
Add the sliding opening and closing functionality. 

**Acceptance Criteria** 

1. As a user, when I open the modal, it opens sliding up from the bottom of the screen. 
2. As a user, when I close the modal, it closes sliding back down.

**Comment by ZoeBeykirch** [comment]
This has been completed, the modals open from the bottom of the screen on mobile in production.
