### ISSUE TITLE
Change GitHub Action to point to OpenSearch 

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-volvotrucks-us#582]
**Description**
As a backend developer, I want to be able to switch the connector from SearchStax to OpenSearch, so that documents are now published on the OpenSearch service backend.

**Business Need**
As the SearchStax licence has expired, and for Volvo Trucks, it was not replaced with OpenSearch previously, search is currently not working in production.
Updates needed to support calls and responses from OpenSearch instead of existing SearchStax index.

**Acceptance Criteria**
- Review the current GitHub Actions workflows to identify all instances where the outdated connector is used.
- Research and document the changes, improvements, and potential breaking changes in the latest version of the connector.
- Update the connector in a development or testing branch to assess any impacts on the existing workflows, including compatibility with other actions and scripts used in the pipelines. (Production page will be used for testing published and unpublished). 
- Update documentation related to the GitHub Actions workflows in our Wiki to reflect the changes made, including new features or parameters introduced with the updated connector.

**Comment by BeckyMedlin** [comment]
@manuel-vara @mollyaljenkins @shirin27 Do we need a front-end ticket to enable search feature for Volvo users?
