### ISSUE TITLE
FR: [v2-hero] – minimal variant

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-volvotrucks-us#601]
### Context/Description

A new variant of the hero that doesn’t contain any media. For use on Magazine landing and other pages.

A similar solution was built for Mack Trucks: https://github.com/Netcentric/vg-macktrucks-com-rd/issues/111

### Acceptance Criteria

**User AC:**
- Button links to the heading in [v2-newsletter] block at the bottom of the page.
- Smooth scrolling is in use

**Editor AC:**
- Should be able to set the variant (e.g. `compact`?)
- Should be able to set the button variant to `marketing-cta`
- Possibility to combine with other modifiers like `centered`

**Non-functional AC:**
- Block is as tall as its contents, with 80px `padding` vertically
- Another variant will need to be added to have a transparent `background-color`

### Note

The current behavior with buttons is that the first button in the block is of type `primary`, and the second button will always be `secondary`. There should be a possibility for editors to select which button should be used (#549)

Assumption that the desktop and tablet designs are the same.

### Technical details

- A different solution than for Mack Trucks is needed, as there is already a 'no-image' [variant available](https://develop--vg-volvotrucks-us--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-hero&index=0)
- By going for a modifier set by the editor, we need to make sure that the block won’t break when combining the modifier with an image or video.

### Attachment / link to Figma

Desktop/Tablet: https://www.figma.com/file/SDLKNiRf0s5Jbhqn9TJZ6H/Magazine?type=design&node-id=1548-4688&mode=design&t=DHv5YVLYEfDrKOHP-4
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/308ce71a-926c-4300-a13d-ec82411a17f8)

Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1598%3A23091&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/44168dad-a496-4333-abea-889e74fd868b)

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results except for below outstanding AC :
1. This variant will have a transparent background-color

**Comment by girishdigrajkar** [comment]
Validated and able to get the expected results and hence, closing the ticket:

<img width="1693" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/cd5b1efb-c5e3-4046-8c8a-77085c3738ad">
