### ISSUE TITLE
FR: implement pagination module for v2-article-cards

### ISSUE THREAD

**Issue by cogniSyb** [hlxsites/vg-volvotrucks-us#602]
### Context/Description

> Pagination allows users to assess the number of pages available, identify what page they are on, browse to the previous or next page, or jump straight to the first or last page.

This component exists already in the Volvo Core Design Kit.

### Acceptance Criteria

**User AC:**
- Buttons are available to navigate forward or backward in pages 

**Editor AC:**
- Aria labels should be editable in the placeholder.xlsx file.
  - The text for the aria labels is available [here](https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs).
- The pagination should display a maximum of 7 pages. If there are more than 7, one or two ellipses will appear within the pagination. For details on how this functionality works, please refer to [this page](https://developer.designsystem.volvogroup.com/?path=/docs/web-components-pagination--docs).
  
**Non-functional AC:**
- Block colors should adapt to their context, ensuring they work on sections with dark or grey backgrounds.
- The code should be reusable so it can be applied to other pages.

### Out of scope

- [ ] #765
- Other variants of pagination as documented in Volvo Core Design Kit
- Sort order of the content within each page
- Checking how many content pages are to be shown per page

### Note
Volvo pagination 
https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs

### Technical details

- Provide semantics, focus on accessibility things like `aria-current="page"`

### Attachment / link to Figma
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/8b12ea7f-2678-418a-905e-f0ac3f43baec)
Figma Design:
Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1590%3A21691&mode=dev
Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1636%3A26829&mode=dev

Volvo Core Design Kit: 
- https://www.figma.com/file/3NXBS8NFxn7TU0lvNDND7f/BETA---Volvo-Core-Design-Kit?type=design&node-id=28027-71762&mode=design&t=xY5KLIjUP1enK6ZY-4
- https://volvoexperincesystem.z6.web.core.windows.net/?path=/docs/web-components-pagination--docs
- https://www.volvogroup.com/experiencesystem/en/#/brand/615bfcc428c818001105b4e3/61a0de32a7047974164f01dd/6230544937a675408d840ec2

**Comment by Joesturbo** [comment]
@mollyaljenkins - can we review this as the design system has this functionality in the design kit. We should be able to reduce the overall time on this item.

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as expected.
