### ISSUE TITLE
Spike: Investigate an Adobe EDS Block that can handle SalesForce Web-To-Case connection

### ISSUE THREAD

**Issue by KJohnsn** [hlxsites/vg-volvotrucks-us#603]
**Non-functional AC:**
- The solution can replace the Alcemer forms that are used for Contact Us 
- The solution can replace the Adobe Form Block with the Adobe Component managing Salesforce web-to-case solution in PartsAsist (separately) 
- Needs to be available for Mack, Volvo, and PartsAsist 
- A filled out form is routed to the right inbox (within the business or to a dealer) and can then be picked up by the right group or local dealer

**User AC:**
- Website visitors can fill out their information on the form, submit the form and be displayed a thank you message 

Note 
- The prior solution suggestion to drop HTML in an Adobe Component Block creates security issues and was rejected 

**Description**
**Web-to-case is a feature that allows businesses to capture customer inquiries directly from their website and automatically convert them into support cases within Salesforce.** This automation improves response times and ensures that customer inquiries are promptly addressed by the appropriate personnel.

The potential Adobe solution would be used to **replace the Alcemer forms that are used for Contact Us.** We would also need to replace the Adobe Form Block with the Adobe Component managing Salesforce Web-to-case Solution in PartsASIST (separately). The initial thinking was that we could possibly drop in HTML in a Adobe Component Block but this introduces a number of security risks which we need to avoid at all costs. And Adobe EDS offers a much simplier way for CMS editors to update, change, and modify content on the fly. 

**Challenge**
There needs to be a bit of research and deep dive with Adobe to see if they have an out of the box solution that we can use for this that doesn't involve Marketo, Workfront, or Fusion connections to be able to manage Salesforce Web-to-case forms that are rendered on the front end using current CSS styling. The forms would then be used by website visitors to fill in and submit with a thank you message showing in place after submital.

**Web-to-case connections, comments**
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/126615590/f02384fe-1d4b-4797-9801-0e4ed5385ad7)

**Use Case**
Website form submissions that can convert to support cases that are routed to either an inbox or to the dealers
So that when a customer fills in a contact us form, the message is routed to the correct inbox
Or that the request gets routed to the dealer
Then the message in the appropriate inbox is picked up by the correct group or local dealer

With solution, we need to create tickets for Volvo Trucks, Mack Trucks, and PartsASIST.

**Comment by Joesturbo** [comment]
SF working on Pardot Forms to web 2 case in SF. Potential existing solution should work as a form handler.

**Comment by ZoeBeykirch** [comment]
Confirmed we can close this ticket.
