### ISSUE TITLE
Bug: Helix 5 Upgrade - Site-wide JavaScript Issues with Modal

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#607]
### Issue Type

Bug

### Summary

[modal] JavaScript Issues 

### Priority

Blocker

### Description

We have found multiple JavaScript related issues on the site that are likely caused by the conversion to Helix v5 and code upgrade:

Modals + videos don't open, and if a user tries to click on a modal afterwards all functions on the page fail. I.e. the user has to refresh the browser and no navigation item work as expected. 

### Affected Device Classes

Desktop, Tablet, Mobile

### Affected Browsers/Devices and Versions

Chrome, Edge, and Safari were tested on desktop computer and iPhone. Likely issues extend to all browsers and devices. 

### Steps to Reproduce
1. Navigate to https://www.volvotrucks.us/trucks/all-new-vnl/#resources
2. When a user clicks on any modal or video block that should enable the functionality to open a new modal secondary page, the modal does not open. For example, click on "+EXPLORE EXTERIOR"
3. Additionally, after a user attempt to click on the modal, all functions on the page fail. For example, after clicking "+EXPLORE EXTERIOR", try to click on any navigation item or button the page - it will not work until the user refreshes their browser page. 
5. Another example is on [Resources](https://www.volvotrucks.us/trucks/all-new-vnl/#resources) section when clicking any of the video thumbnails. 
6. Investigation is that a Javascript failure causes this issue. 

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/4598f997-6e50-4376-a8a3-17be279fb302)

**Comment by ZoeBeykirch** [comment]
These bugs are no longer on prod now that the Helix 5 upgrade was reverted, but when we do the upgrade, we should be aware of how to address these issues.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results: 
No JS error displayed ( Below screenshot has a warning which is developer helpful info however it is not an error as validated with dev(Syb) ) 

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/a615a414-e125-4ef6-a8a9-a1b24c72dd54)
