### ISSUE TITLE
Bug: Cookies Consent Bar Keeps Popping Up in Pre-Prod  

### ISSUE THREAD

**Issue by Varunvolvo** [hlxsites/vg-volvotrucks-us#612]
### Issue Type

Bug

### Summary

Cookie Consent issue is present on the dev pre-production environment only where the consent message continues to pop up, even after the user has accepted all cookies. Issue is not present on production environment. 

### Priority

Medium

### Description

The cookies keeps on popping up again even after accepting it multiple times. Example: https://main--vg-volvotrucks-us--hlxsites.aem.page/

![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/139381543/34ae0421-5e15-4bed-9f8c-73a5eb637f3e)

### Affected Device Classes

Desktop

### Affected Browsers/Devices and Versions

all browsers

### Steps to Reproduce

Added the screenshot of the issue

### Expected Results

The cookie bar should not popup once accepted

### Actual Results

The cookie bar should  pops up even after accepting

### Related tickets
https://github.com/hlxsites/vg-roadchoice-com/issues/228
https://github.com/hlxsites/vg-macktrucks-com/issues/698
https://github.com/hlxsites/vg-volvotrucks-us/pull/604
https://github.com/hlxsites/vg-partsasist/issues/112

**Comment by BeckyMedlin** [comment]
Per @Varunvolvo this may be the result of adding .aem.page to the domain. If it's added to Mack, it may cause an issue there.

**Comment by BeckyMedlin** [comment]
Injecting into Sprint 2 as it is causing a poor user experience

**Comment by girishdigrajkar** [comment]
Validated the pages and result is acceptable as no cookies triggered :
1. https://612-onetrust-config--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnr-electric/  >>  shows 'Change cookie settings" ; when clicked nothing happens :  As expected for disabling cookie functionality
2.  https://612-onetrust-config--vg-volvotrucks-us--hlxsites.aem.page/   clicking on it takes to https://www.volvotrucks.us/cookies/ so branch url page does not enable cookies of branch domain.
3. https://612-onetrust-config--vg-volvotrucks-us--hlxsites.aem.page/trucks/vnr-electric/specifications/    shows "change cookie settings " when clicked nothing happens :  As expected for disabling cookie functionality
