### ISSUE TITLE
FR: Apply redesign typography on magazine article

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#633]
### Context/Description

As a content author, I would like to apply the redesign typography text to my magazine articles so that my article headlines, body paragraphs, and section titles are more visually appealing to the readers. 

### Acceptance Criteria

**User AC:**
- [ ] The article headline shall be displayed using heading 3.5 for desktop and tablet devices, and heading 5 on mobile devices.                      
- [ ] The paragraph body text shall be displayed as body regular 2 on desktop and tablet devices, and body regular for mobile devices. 
- [ ] The section title shall be displayed as heading 4 on desktop and tablet devices, and heading 5.5 on mobile devices.

**Editor AC:**
- [ ] Editors can freely use text on magazine article pages outside of predefined blocks, with the style settings automatically determining the appropriate heading tag (H tag).

**Non-functional AC:**
- [ ] The article headline shall be displayed under the hero with 80 px of padding above, and 48 px of padding beneath.  
- [ ] The paragraph body text shall have 24 px of padding below and beneath as a default between images and other body paragraph text lines. The padding shall increase to 48 px between an article headline or section title text component. 
- [ ] The section title shall have 24 px of padding below and beneath as a default, with an extra padding block of 48 px above to show a clear break between paragraph body text. 
- [ ] Text can be compatible with using a white, grey, or black background. 

### Attachment / link to Figma

**Article headline**
  - Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1571%3A20511&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/a3d8cbfd-b484-44e5-b722-5fd46ec58013)

  - Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1602%3A25778&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/611cc909-71e0-44e8-a4a6-0431410d1281)

**Paragraph body text**
  - Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1571%3A20521&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/62c90a57-0e9f-44c0-a54e-098b6e8d0a3c)

  - Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1602%3A25791&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/5c394fc9-415a-4c8d-a721-1983bc8961f3)

**Section title**
  - Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1626%3A26741&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/d9e4a2cf-46a2-493d-8c48-883644feef81)

  - Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1602%3A25794&mode=dev
 ![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/c7774889-4ee3-482c-a895-0a337fe0300d)

**Comment by amglebihan** [comment]
The ticket is now blocked as we await feedback from the design team on the headings' styling.

**Comment by BeckyMedlin** [comment]
Courtney at Code and Theory responded (see attachments):

![2024-07-30_Courtney_CandT message](https://github.com/user-attachments/assets/7b1e3620-843b-418c-9400-07389658485b)
![Screenshot 2024-07-29 at 11 56 44 AM](https://github.com/user-attachments/assets/326d03f9-9c0d-4763-beff-7f9d742a6383)
![Text styles](https://github.com/user-attachments/assets/4c9fbc18-b1c0-40ac-b645-c0b204ce61c6)

**Comment by amglebihan** [comment]
- To set the article headline, use the v2-text block, as its styling in Figma (heading 3.5) falls between heading 3 and heading 4. Place a v2-text block on the page and apply the heading-3-5 modifier to it: v2-text(heading-3-5).
- To set the section title, there is no need to use the v2-text block. Just add its text and set its style to heading 4.

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, this ticket could be closed

**Desktop:**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/79f0c27b-a5d4-47bd-a01f-17cc48c2a8e5">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/dc6ddf24-4167-4c79-8c36-2d1b81758a1b">

**Mobile:**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/757bfe2e-1adb-42df-be42-452536e3ea4e">

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/e76a725a-1e1f-4b74-b38c-61a620c6296b">

**Comment by ZoeBeykirch** [comment]
> * To set the article headline, use the v2-text block, as its styling in Figma (heading 3.5) falls between heading 3 and heading 4. Place a v2-text block on the page and apply the heading-3-5 modifier to it: `v2-text(heading-3-5)`.
> * To set the section title, there is no need to use the v2-text block. Just add its text and set its style to heading 4.
> * As the magazine article page has different styles compared to other VT pages, the class v2-magazine-article has to be added to the page's metadata's style property (e.g. `redesign-v2, v2-magazine-article`)

@amglebihan Can we add this important info to the Sidekick library?
