### ISSUE TITLE
FR: [V2 Quote] - Inline Variant

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#635]
### Context/Description

As a content author, I want to use a quote block harmoniously within my magazine articles to elevate our storytelling, allowing impactful quotes to stand out in a seamless way to enhance the reading experience. 

### Acceptance Criteria

**User AC:**
- As a user, I shall see the quote block seamlessly integrated within the article text and images. 
- As a user, I shall see the quote text displayed in black color using heading 3 size for desktop/tablet devices, and heading 4 for mobile devices. 
- As a user, I shall see the quote author text displayed in greyscale 600 using body regular 2 size for desktop/tablet devices, and body regular for mobile devices. 

**Editor AC:**
- As an editor, I can use this block on any page. 
- As an editor, I can find this block in the Sidekick library. 

**Non-functional AC:**
- This block can be compatible with using a white, grey, or black background.
- The default padding for this block on desktop shall be 24px above and below the block, and 16px between the quote and author line. On mobile, the padding default shall be 16px above and below the block, and 8px between the quote and author line. 

### Attachment / link to Figma

Desktop/Tablet: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1626%3A26709&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/6cce64b1-86fd-487a-935b-f14162c648a5)

Mobile: https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1518%3A6694&mode=dev
![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/ed4a9fb9-dc1b-44dd-84a7-1cd4bab72bdd)

**Comment by girishdigrajkar** [comment]
Validated and able to see correct results hence, marking the ticket to closed status:

<img width="1695" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/2f3225a1-bbef-4b7f-9dea-4f041c5a6ae3">

<img width="1695" alt="image" src="https://github.com/hlxsites/vg-volvotrucks-us/assets/125972657/cf984a67-0c7a-4ef7-84da-ec5487deb358">

Note:This block will be added to sidekick library by @cogniSyb later i.e. after testing activity / deployment.
