### ISSUE TITLE
Bug: AEM Assets no longer has video option on filter

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#668]
### Issue Type

Bug

### Summary

AEM Assets no longer has video functionality. This is blocking new videos from being uploading to the website via AEM Assets. 

### Priority

Blocker

### Description

The video functionality for content editors uploading new videos is no longer available in AEM Assets. As recently as last week content editors could choose a video to upload via AEM Assets, and this is no longer present. 
Videos that were previously uploaded with AEM Assets are still working, so this is only blocking new uploads. 

### Affected Device Classes

Desktop

### Affected Browsers/Devices and Versions

All browsers. AEM Assets is only used on Desktop devices. 

### Steps to Reproduce

1. Navigate to any word document in the Mack SharePoint. 
2. Activate the AEM Sidekick tool
3. Click on "My Assets" which is the button next to the Library
4. Log in to Adobe is required if this is your first time loading AEM Assets from the Sidekick. 
5. Make sure Delivery-North America Prod repo is selected from the Repository dropdown. 
6. Under Files, see how video is not an option when it was listed before. 
7. Click on the filter by the search bar, and see how there is no longer a video option present. 

### Expected Results

There should be a video file option in the filter results to make it possible for see and use video files. 

### Actual Results

![Image](https://github.com/hlxsites/vg-macktrucks-com/assets/125895595/5310176a-fc80-40c6-8904-89aa3830d23f)

**Comment by girishdigrajkar** [comment]
Assets section shows loading however, nothing happens :

![image](https://github.com/user-attachments/assets/477d24e4-6471-4625-be56-c63ab095b2da)

**Comment by girishdigrajkar** [comment]
Validated along with Kannan and able to see correct results below :
![image](https://github.com/user-attachments/assets/0e226718-fb10-4f51-b676-6f87f0ecf41b)

![image](https://github.com/user-attachments/assets/3a068e35-cc1d-4b5c-8c48-b315d15ec375)
