### ISSUE TITLE
Defect: Incorrect title, logo size, top links alignment and search box is missing 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#67]
Defect: Incorrect title, logo size, top links alignment and search box is missing 

**Steps:**
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/
2. Validate the page title, logo, links at the top of the page such as Find a Dealer, Purchase A Truck ,USA, Volvo store, Log In
3. Validate the search box

**Expected:**
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/125972657/223064636-29b339c4-1767-4dd3-a438-ef0011645681.png">

**Actual:**
Incorrect title, logo size, top links alignment and search box is missing 
![image](https://user-images.githubusercontent.com/125972657/223064473-439829a0-fe12-4275-8ede-2aac44ec2243.png)

**Comment by Buuhuu** [comment]
Still in progress, please see #4
