### ISSUE TITLE
FR: V2 Explore Magazine Dynamic Feed

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#680]
### Context/Description

As a Volvo Trucks magazine content editor, I want to create a new dynamic block for the article page feed so that newly published articles are automatically added based on their publish date, eliminating the manual effort of updating the feed page. 

### Acceptance Criteria

**User AC:**
- [ ] On mobile devices, cards are displayed on top of each other
- [ ] On desktop and tablet devices, the cards are displayed in a three-column grid
  - The cards have a maximum width of `21rem`, as in use elsewhere in VT
- [ ] The entire card is clickable and links to the magazine article page
- [ ] The hover state of the tertiary button is shown when hovering the card
- [ ] The main link text will be the title of the article, so that the SEO and accessibility guidelines are followed
- [ ] All cards in the same row will be the same height 

**Nonfunctional AC:**
- [ ] Logic is introduced so that the block can automatically update when new articles are published to always display the most recent articles without requiring manual interventions from editors. 
- [ ] Articles appear in descending order based on their publish date, with the most recent articles appearing first.
- [ ] Card element contains: 
  - Image thumbnail
  - Article Title
  - Metadata text for date above the article title
  - Tertiary button

### Out of scope

- Pagination will be taken up in a [separate ticket.](https://github.com/hlxsites/vg-volvotrucks-us/issues/602) 
- Logic for removing duplicate articles will be taken up in a [separate ticket](https://github.com/hlxsites/vg-volvotrucks-us/issues/681) 
- 3 cards with grey backgrounds directly above this block will be taken up in a [separate ticket. ](https://github.com/hlxsites/vg-volvotrucks-us/issues/619)

### Attachment / link to Figma

**Desktop/Tablet:** https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1518%3A6694&mode=dev

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/af523a88-fdd8-4f4c-94e2-a8056d8b35c2)

**Mobile:** https://www.figma.com/file/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?type=design&node-id=1518%3A6694&mode=dev

![Image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/0d2a6753-820a-44d6-ba49-5b77785ec7b9)

### Related Ticket 
https://github.com/hlxsites/vg-macktrucks-com/issues/602

### Note

The styling of "[V2 Resources Gallery](https://www.volvotrucks.us/trucks/all-new-vnl/#resources)" follows the desired design, but would require images instead of videos, remove the section heading, and removes tertiary button toggle requirements.  
![image](https://github.com/hlxsites/vg-volvotrucks-us/assets/125895595/628e8620-b30d-4915-999c-25a6cf595aaf)

**Comment by AsmitKMishra** [comment]
Testing Completed:
1. Dimensions are within margin with Figma.
2. Entire card is clickable.
3. Hover state of the tertiary button is shown when hovering the card.
4. Cards in the same row are of same height.
