### ISSUE TITLE
Bug: [Volvotrucks.us] Blank page displayed when clicked on Explore safety link for the second time

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#698]
### Issue Type

Defect

### Summary

[Volvotrucks.us] Blank page displayed when clicked on Explore safety link

### Priority

Medium

### Description

Blank page displayed when clicked on Explore safety link

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

Steps:
1. Navigate to https://main--volvotrucks-us--volvogroup.aem.page/
2. Click on Trucks tab >>.  Click on **all-new- Volvo vnl**
3. Under Safety section click on **+ Explore safety**
4.  Verify the page

### Expected Results

Expected : Page should be displayed with valid content

### Actual Results

Actual: Blank page is displayed 

### Attachment

<img width="1728" alt="Screenshot 2024-08-12 at 4 27 27 PM" src="https://github.com/user-attachments/assets/3c04d941-4685-4faf-8604-6f2278bf9e5f">

Reference: https://ncchat.slack.com/archives/C04P8KH8C4D/p1723190749473429

**Comment by cincplug** [comment]
Reopening since it was auto-closed by accidental premature merge into main instead of develop

**Comment by silviulungu** [comment]
Testing completed, everything works well.
