### ISSUE TITLE
FR: Remove Automatic All Caps from Magazine Feed Titles

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-volvotrucks-us#702]
### Context/Description

As a Volvo Trucks magazine content author, I want the new article feed blocks to retain the title capitalization specified in the article metadata, so that my magazine article titles are not automatically displayed in all caps.

### Acceptance Criteria

**Non-functional AC:**
- [x] The new magazine feed blocks must not automatically convert titles to all caps. 
- [x] Titles should appear in their original capitalization as set in the article metadata.

### Note

Affected tickets: 
https://github.com/hlxsites/vg-volvotrucks-us/issues/619
https://github.com/hlxsites/vg-volvotrucks-us/issues/680

### Attachment / link to Figma

<img width="247" alt="image" src="https://github.com/user-attachments/assets/8b3db3bf-c22b-42a3-aa48-c2f16d362b3f">

Desktop: https://www.figma.com/design/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?node-id=1569-17869&m=dev

<img width="136" alt="image" src="https://github.com/user-attachments/assets/af3d5349-158c-494f-9581-a2cb2956756b">

Mobile: https://www.figma.com/design/c2jG1bOcvle2bCmZqgptyS/Magazine-C%26T?node-id=1518-6694&m=dev

**Comment by AsmitKMishra** [comment]
Testing Completed. Feature works as expected.
Before:
<img width="644" alt="art2" src="https://github.com/user-attachments/assets/012769a9-537d-471f-8d65-72673a1b0236">
After:
<img width="633" alt="art" src="https://github.com/user-attachments/assets/c91e1b56-a7ed-402c-943d-820e46453a75">
