### ISSUE TITLE
Bug: Volvo Truck Builder performance issue

### ISSUE THREAD

**Issue by BeckyMedlin** [hlxsites/vg-volvotrucks-us#735]
### Issue Type

Bug

### Summary

Volvo Truck Builder renders slowly or not at all

### Priority

Blocker

### Description

Initially, when accessing the Build Yours button on the home page this morning, the new page opens, but nothing renders. This seems to have been corrected; however, @ZoeBeykirch used a private window and still sees a delay in loading (about 3 seconds) and still seeing the spin wheel pop up for a second between next steps/colors.

Rapid Images is investigating a script called delayed.js. 

Please investigate on front-end to determine if there's a cause for the performance delay.  

### Affected Device Classes

Desktop

### Affected Browsers/Devices and Versions

Chrome and Edge

### Steps to Reproduce

Navigate to www.volvotrucks.us, scroll down homepage to select "Build Yours" button. Truck Builder loads with about a 3 second delay and spin wheel displays before rendering.

### Expected Results

Expected behavior is that the Truck Builder will load and render without delay.

### Actual Results

Performance issue with loading and rendering the Truck Builder.

**Comment by ZoeBeykirch** [comment]
Replacing the iframe with embed solution should improve this performance: https://github.com/hlxsites/vg-volvotrucks-us/issues/704

**Comment by cincplug** [comment]
The loading speed of images in truck builder is out of our hands because our JS block only loads the iframe which handles it all, and we have no influence on what happens within the iframe. I'll work on #704 assuming that it will improve the performance of truck builder.
