### ISSUE TITLE
Bug: Volvotrucks FR Recalls page not working

### ISSUE THREAD

**Issue by alexiscoelho** [hlxsites/vg-volvotrucks-us#769]
### Issue Type

Bug

### Priority

Blocker

### Description

~~The following page is not working:~~
https://www.volvotrucks.us/fr/recalls/

UPDATE:
In the light of the latest developments, VolvoTrucks supports multi language sites. `/fr/` matches what is expected of a folder of a language of this site, it is expected that a language folder has a constants.xlsx file, this piece of logic was breaking the loading of the page since it was looking for the constants file in the `/fr/` folder.
A quick fix was done and the main constants file was copied and published under the `/fr/` folder.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All

### Steps to Reproduce

1. Go to:
https://www.volvotrucks.us/fr/recalls/
2. The page doesn't load
3. The attached screenshot shows the error on the console

### Expected Results

The page loads properly without a constant file in the `/fr/` folder

### Actual Results

The page is black with errors in the console. The constant file is not loaded from the parent folder, instead tries to load it from the `/fr/` folder

### Attachment

<img width="812" alt="Screenshot 2024-10-02 at 11 21 12" src="https://github.com/user-attachments/assets/1de75df7-157a-478b-887c-5753f8b9136b">

**Comment by alexiscoelho** [comment]
Solved by configuring a redirect on the redirects sheet to redirect the request from `/fr/constants.json` to  `/constants.json`

**Comment by girishdigrajkar** [comment]
@alexiscoelho:  
Able to see the page ( when fr folder does not have any 'constant.xls' file :
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/caf47f8f-5b55-4558-9677-bf7cf24dcd20">

Below error related to localhost is displayed:
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/2ec6f8f2-25e5-4c36-9ae5-ba858f167498">

Also, the Network tab shows 3 constants.json file fetches;  last one shows no contents however, second file is from  sharepoint  volvotrucks.us SP folder.

**Comment by girishdigrajkar** [comment]
For above observations dev confirmed to ignore as not relevant to this ticket and as mentioned in above comment able to see the page hence, closing the bug.
