### ISSUE TITLE
Teaser Cards

### ISSUE THREAD

**Issue by hannessolo** [hlxsites/vg-volvotrucks-us#8]
Build a component for teaser cards, with support for 3 columns and 2 columns

https://www.volvotrucks.us/

<img width="1264" alt="Screenshot 2023-02-15 at 14 27 50" src="https://user-images.githubusercontent.com/24207564/219055281-c3e91d72-a9de-4751-9483-975bfcdef50c.png">
<img width="1254" alt="Screenshot 2023-02-15 at 14 54 17" src="https://user-images.githubusercontent.com/24207564/219062747-cde8c100-2623-4f7f-bab9-76fc6f2e0e48.png">

**Comment by hannessolo** [comment]
In the first picture, the heading has a link on it, and in the second picture, the heading doesn't have a link on it. (Decides whether there is a > or not).

**Comment by msagolj** [comment]
@hannessolo please not that does two are actually not quite the same:
- the 2 colums are indeed teaser cards it seems
- the 3 columns are news items, they behave slighty different (e.g. different font size depening on breakpoint)
