### ISSUE TITLE
Defect: Minor:  Global styling related - Font and image issues observed 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#80]
Steps:
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/news-and-stories/press-releases/2023/february/vt-showcases-proof-points-on-freight-efficiency-sustainability-and-maximizing-uptime-at-tmc-2023
2. Validate the font and image styling
3. Click on 'Volvo Trucks global organization' & 'Volvo Group' links under 'Download Press Release Images'  section
Expected:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/223349476-00bc8c48-6a14-479b-93a6-97456428906e.png">

Actual:
1. Font expected is 24px whereas it is 36px also, images are not horizontally aligned.  
2. The link should open a new tab instead it navigates to the page within tab
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/223349360-89548eb2-79ae-40ca-a920-54cf22975806.png">

**Comment by girishdigrajkar** [comment]
Validated on publish and unable to see the changes hence, issue is not closed, please investigate:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/224935400-853770ec-21fe-484c-aaee-b64cbde96145.png">

**Comment by andreibalanescu** [comment]
Hi @girishdigrajkar , can you please double check the URL, as I get 404 when I try to access it?

**Comment by andreibalanescu** [comment]
Hi @girishdigrajkar , this has been done. Please review and let me know regarding ticket closure.

**Comment by girishdigrajkar** [comment]
Able to get the expected results and hence, closing the defect:

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/233926028-9d75a886-891d-4627-82c4-74b3cf824e3c.png">
