### ISSUE TITLE
Defect: Cookie Page: Multiple issues related to page title logo, button text & font issues observed 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-volvotrucks-us#98]
**Steps:**
1. Navigate to https://main--vg-volvotrucks-us--hlxsites.hlx.page/cookies/
2. Validate the page title logo
3.  Validate 'cookie setting' / 'Cookie Preference Centre >'  button
4.   Validate the font of the text

**Expected:**
1. Page title logo expected is:
<img width="1782" alt="image" src="https://user-images.githubusercontent.com/125972657/224760036-8dbd4608-d059-4554-9062-0d6f4b202449.png">

2. Expected text of button is 'Cookie Preference Centre >'
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/224760216-e1e6f4af-30fc-48eb-a4c0-fe59446fca89.png">

**Actual:**
1. Page title logo is missing :
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/224760479-5d0aa3d1-f4c2-48b9-9816-c5ffa975f7b4.png">

2. Button text is not as expected:
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/125972657/224760766-6e2a0b65-91d9-4259-b4f1-6ce5596dbb79.png">

3. Fonts are not as expected, please see below detailed analysis: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/m_ambin03198/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/m_ambin03198/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

TEXT ON   PAGE | EXPECTED | ACTUAL
-- | -- | --
COOKIE NOTICE | FONT: 60PX  VOLVOBROADPRODIGITAL, SANS SERIF | FONT: 48PX   VOLVONOVUM-MEDIUM
This cookie notice describes how AB Volvo, company registration   number 556012-5790 having its registered address at AB Volvo, Gropegårdsgatan   2, 41710 GÖTEBORG hereinafter referred to as “Volvo”, “we”, “us”, uses   cookies at www.volvotrucks.us.          AB Volvo is the controller for the use of cookies on the website as well as   for processing of your personal data that is collected through cookies when   you visit www.volvotrucks.us. For further information about our processing of   personal data through cookies, please see our Website notice   www.volvogroup.com/en/tools/privacy.html. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16PX  VOLVONOVUM, SANS SERIF
What is a   Cookie? | FONT: 24PX    VOLVONOVUMMEDIUM   SANS SERIF | FONT: 36PX  VOLVONOVUMMEDIUM
A cookie is a small piece of data sent from a webpage and stored   in a user's web browser, mobile phone, or other device while the user is   browsing that webpage. A cookie can help the webpage provider to recognize   your device the next time you visit that webpage, provide you with access to   certain functions on the webpage and/or register your surf patterns.          There are two types of cookies, persistent cookies and session cookies.   Session cookies are stored temporarily when you as a visitor visit and browse   our website and are deleted when you close your web browser. Persistent   cookies are stored as a file on the computer during a period of time, until   you as a visitor or the server that sent them, delete them.          Furthermore, cookies can be divided into first and third-party cookies.   First-party cookies are set by the website owner and third-party cookies are   set by another website.          There are other technologies such as pixel tags, web bugs, web storage and   other similar files and technologies that may carry the same functions as   cookies. In this cookie notice, we use the term “cookies” for cookies and all   such similar technologies.          For more general information about cookies, please see www.aboutcookies.org  and/or www.allaboutcookies.org.          If you do not allow this website to use cookies, then certain features or   sections of this site may not be available to you or may not function as   expected. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16PX  VOLVONOVUM
Which cookies   does the website use? | FONT: 24PX  VOLVONOVUMMEDIUM | FONT: 36PX  VOLVONOVUMMEDIUM, SANSSERIF
We   use the following cookies for the purposes set out below: | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16PX  VOLVONOVUM
Cookie List | FONT: 15PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 27PX  VOLVONOVUM
A cookie is a   small piece of data (text file) that a website – when visited by a user –   asks your browser to store on your device in order to remember information   about you, such as your language preference or login information. Those   cookies are set by us and called first-party cookies. We also use third-party   cookies – which are cookies from a domain different than the domain of the   website you are visiting – for our advertising and marketing efforts. More   specifically, we use cookies and other tracking technologies for the   following purposes: | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
Strictly   Necessary Cookies | FONT: 10PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 18PX  VOLVONOVUM
These cookies   are necessary for the website to function and cannot be switched off in our   systems. They are usually only set in response to actions made by you which   amount to a request for services, such as setting your privacy preferences,   logging in or filling in forms. You can set your browser to block or alert   you about these cookies, but some parts of the site will not then work. These   cookies do not store any personally identifiable information. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
All Table   headers | FONT: 9PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
All Table rows | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
Performance Cookies | FONT: 10PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 18PX  VOLVONOVUM
These cookies   allow us to count visits and traffic sources so we can measure and improve   the performance of our site. They help us to know which pages are the most   and least popular and see how visitors move around the site. All information   these cookies collect is aggregated and therefore anonymous. If you do not   allow these cookies we will not know when you have visited our site, and will   not be able to monitor its performance. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
Functional Cookies | FONT: 10PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 18PX  VOLVONOVUM
These cookies   enable the website to provide enhanced functionality and personalisation.   They may be set by us or by third party providers whose services we have   added to our pages. If you do not allow these cookies then some or all of   these services may not function properly. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
Targeting Cookies | FONT: 10PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 18PX  VOLVONOVUM
These cookies   may be set through our site by our advertising partners. They may be used by   those companies to build a profile of your interests and show you relevant   adverts on other sites. They do not store directly personal information, but   are based on uniquely identifying your browser and internet device. If you do   not allow these cookies, you will experience less targeted advertising. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16.2PX  VOLVONOVUM
How do I change my cookie settings? | FONT: 24PX  VOLVONOVUMEDIUM, SANS SERIF | FONT: 36PX  VOLVONOVUM-MEDIUM
Consenting   to our use of cookies is optional and you can at any time choose to withdraw   your consent. All cookies except necessary cookies will be removed. To   withdraw your consent, please visit Cookie   preference center, or click the blue shield icon   (Cookie settings) at   the bottom left corner of each page.          You can block some cookies through your browser settings. In such case,   your browser automatically rejects use of such cookies or informs you every   time a website (such as ours) requests to use cookies. Please see more   specific information below          After your visit to our website you can review and delete any permanent   cookies that have been stored on your browser. To make identifying our   cookies easier we have provided the name of each cookie in the table   above.          Specifically about browser settings          Many web browser settings allow you to view and delete cookies from your   computer and disable or block the installation of cookies on your computer.   Below you can find relevant instructions for the different browsers:          Chrome (link: https://support.google.com/)          Safari (link: https://support.apple.com/)          Safari on iPhone and iPad (link: https://support.apple.com/)          Internet Explorer and Microsoft Edge (link:   https://support.microsoft.com/)          Firefox (link: https://support.mozilla.org/)          Opera (link: https://www.opera.com/help/tutorials/security/privacy/)          Future changes          We reserve the right to update and change this cookie notice from time to   time, including as required by applicable laws and regulations. | FONT: 16PX  VOLVONOVUMREGULAR, SANS SERIF | FONT: 16PX  VOLVONOVUM
Questions? | FONT: 24PX  VOLVONOVUMEDIUM, SANS SERIF | FONT: 36PX  VOLVONOVUMMEDIUM
If you have any questions or comments about our use of cookies,   please contact groupinfo@volvo.com or go to Volvo Group - Privacy for more   information. | FONT: 16PX  VOLVONOVUREGULAR, SANS SERIF | FONT: 16PX  VOLVONOVUM

</body>

</html>

**Comment by Buuhuu** [comment]
@synox while working on that can you implement the general styling for all the heading types in all places? 

So far I found h1-h4. Some headings have block specific stylings (e.g. teaser cards & teaser grid). Some headings and texts are center aligned. For that we could introduce a text bock that just applies some styles like:

| Text (center) |
| --- |
| h2. Lorem Ipsum | 
| p. this is some text |

That could be useful to cover for example https://www.volvotrucks.us/trucks/vnr-electric/ (Taking you Further with Electric) and all the h4/h2 heading pairs later on the page.

However, the default should be left aligned as shown in the press releases or the cookie notice. 

@dkuntze fyi. Also relevant for the import!

**Comment by synox** [comment]
@Buuhuu I created a minimal text-block impl in #109. Note that it competes with https://github.com/hlxsites/vg-volvotrucks-us/blob/eb1604d7711092700cd3b1c155ec72eb39fb0f7a/styles/styles.css#L156-L158 and can yield undefined results if used inconsistently.

**Comment by synox** [comment]
@girishdigrajkar I addressed all issues.

Regarding the `Cookie List` and following, I did not match it 100% with production, but instead used heading-sizes that make more sense. 

https://98-cookie-style--vg-volvotrucks-us--hlxsites.hlx.page/cookies/

**Comment by Buuhuu** [comment]
```
[data-align="center"] { 
   text-align: center; 
}
```
is unreliable  as it does not work in all places. We should probably remove it.

**Comment by girishdigrajkar** [comment]
Validated on https://main--vg-volvotrucks-us--hlxsites.hlx.page/cookies/ and able to see correct results.
( font changes were discussed in daily call on 17/3 and confirmed) hence, agree to defect closure.
